import { ToolCategoryDefinition, ToolDefinition } from '@/types/tool';

export const tools: ToolDefinition[] = [
  {
    id: 'pdf-merge',
    name: 'PDF Merge',
    category: 'pdf',
    description: 'Combine multiple PDF files into one document.',
    accept: '.pdf',
    multiple: true,
    tags: ['pdf', 'merge', 'combine'],
  },
  {
    id: 'pdf-split',
    name: 'PDF Split',
    category: 'pdf',
    description: 'Split a PDF into one file per page.',
    accept: '.pdf',
    tags: ['pdf', 'split'],
  },
  {
    id: 'pdf-rearrange',
    name: 'PDF Rearrange',
    category: 'pdf',
    description: 'Reorder PDF pages by page number.',
    accept: '.pdf',
    tags: ['pdf', 'reorder'],
    options: [
      {
        key: 'order',
        label: 'Page order',
        type: 'text',
        defaultValue: '',
        placeholder: 'e.g. 3,1,2',
      },
    ],
  },
  {
    id: 'pdf-rotate',
    name: 'PDF Rotate',
    category: 'pdf',
    description: 'Rotate every page in a PDF.',
    accept: '.pdf',
    tags: ['pdf', 'rotate'],
    options: [
      {
        key: 'degrees',
        label: 'Rotation',
        type: 'select',
        defaultValue: 90,
        options: [
          { label: '90 degrees', value: 90 },
          { label: '180 degrees', value: 180 },
          { label: '270 degrees', value: 270 },
        ],
      },
    ],
  },
  {
    id: 'pdf-delete-page',
    name: 'PDF Delete Page',
    category: 'pdf',
    description: 'Remove selected pages from a PDF.',
    accept: '.pdf',
    tags: ['pdf', 'delete'],
    options: [
      {
        key: 'pages',
        label: 'Pages to delete',
        type: 'text',
        defaultValue: '',
        placeholder: 'e.g. 2,5',
      },
    ],
  },
  {
    id: 'pdf-add-page-numbers',
    name: 'PDF Add Page Numbers',
    category: 'pdf',
    description: 'Stamp page numbers onto a PDF.',
    accept: '.pdf',
    tags: ['pdf', 'numbering'],
    options: [
      {
        key: 'startNumber',
        label: 'Start number',
        type: 'number',
        defaultValue: 1,
        min: 1,
      },
      {
        key: 'fontSize',
        label: 'Font size',
        type: 'number',
        defaultValue: 12,
        min: 8,
        max: 72,
      },
    ],
  },
  {
    id: 'pdf-extract-images',
    name: 'PDF Extract Images',
    category: 'pdf',
    description: 'Render each PDF page as a PNG image.',
    accept: '.pdf',
    tags: ['pdf', 'extract', 'images'],
  },
  {
    id: 'pdf-compress',
    name: 'PDF Compress',
    category: 'pdf',
    description: 'Re-save a PDF with compact object streams.',
    accept: '.pdf',
    tags: ['pdf', 'compress'],
  },
  {
    id: 'pdf-to-png',
    name: 'PDF to PNG',
    category: 'pdf',
    description: 'Convert PDF pages to PNG images.',
    accept: '.pdf',
    tags: ['pdf', 'png', 'convert'],
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    category: 'pdf',
    description: 'Convert PDF pages to JPG images.',
    accept: '.pdf',
    tags: ['pdf', 'jpg', 'convert'],
    options: [
      {
        key: 'quality',
        label: 'JPG quality',
        type: 'range',
        defaultValue: 0.85,
        min: 0.3,
        max: 1,
        step: 0.05,
      },
    ],
  },
  {
    id: 'pdf-to-webp',
    name: 'PDF to WEBP',
    category: 'pdf',
    description: 'Convert PDF pages to WEBP images.',
    accept: '.pdf',
    tags: ['pdf', 'webp', 'convert'],
    options: [
      {
        key: 'quality',
        label: 'WEBP quality',
        type: 'range',
        defaultValue: 0.85,
        min: 0.3,
        max: 1,
        step: 0.05,
      },
    ],
  },
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    category: 'pdf',
    description: 'Combine multiple images into a single PDF.',
    accept: '.png,.jpg,.jpeg,.webp,.gif,.tif,.tiff',
    multiple: true,
    tags: ['image', 'pdf', 'convert'],
  },
  {
    id: 'image-resize',
    name: 'Resize Image',
    category: 'image',
    description: 'Resize images to a target width and height.',
    accept: 'image/*',
    tags: ['image', 'resize'],
    options: [
      { key: 'width', label: 'Width', type: 'number', defaultValue: 1280, min: 16 },
      { key: 'height', label: 'Height', type: 'number', defaultValue: 720, min: 16 },
      {
        key: 'format',
        label: 'Output format',
        type: 'select',
        defaultValue: 'image/png',
        options: [
          { label: 'PNG', value: 'image/png' },
          { label: 'JPG', value: 'image/jpeg' },
          { label: 'WEBP', value: 'image/webp' },
        ],
      },
    ],
  },
  {
    id: 'image-compress',
    name: 'Compress Image',
    category: 'image',
    description: 'Reduce image file size with quality control.',
    accept: 'image/*',
    tags: ['image', 'compress'],
    options: [
      {
        key: 'quality',
        label: 'Quality',
        type: 'range',
        defaultValue: 0.75,
        min: 0.2,
        max: 1,
        step: 0.05,
      },
      {
        key: 'format',
        label: 'Output format',
        type: 'select',
        defaultValue: 'image/jpeg',
        options: [
          { label: 'JPG', value: 'image/jpeg' },
          { label: 'WEBP', value: 'image/webp' },
          { label: 'PNG', value: 'image/png' },
        ],
      },
    ],
  },
  {
    id: 'image-crop',
    name: 'Crop Image',
    category: 'image',
    description: 'Crop images to an exact rectangle.',
    accept: 'image/*',
    tags: ['image', 'crop'],
    options: [
      { key: 'x', label: 'X', type: 'number', defaultValue: 0, min: 0 },
      { key: 'y', label: 'Y', type: 'number', defaultValue: 0, min: 0 },
      { key: 'width', label: 'Width', type: 'number', defaultValue: 512, min: 1 },
      { key: 'height', label: 'Height', type: 'number', defaultValue: 512, min: 1 },
    ],
  },
  {
    id: 'image-flip',
    name: 'Flip Image',
    category: 'image',
    description: 'Flip images horizontally or vertically.',
    accept: 'image/*',
    tags: ['image', 'flip'],
    options: [
      { key: 'horizontal', label: 'Flip horizontally', type: 'checkbox', defaultValue: true },
      { key: 'vertical', label: 'Flip vertically', type: 'checkbox', defaultValue: false },
    ],
  },
  {
    id: 'image-rotate',
    name: 'Rotate Image',
    category: 'image',
    description: 'Rotate images by a custom angle.',
    accept: 'image/*',
    tags: ['image', 'rotate'],
    options: [
      { key: 'degrees', label: 'Rotation', type: 'number', defaultValue: 90, min: 0, max: 360 },
    ],
  },
  {
    id: 'image-pixelate',
    name: 'Pixelate Image',
    category: 'image',
    description: 'Apply a pixelation effect to images.',
    accept: 'image/*',
    tags: ['image', 'pixelate'],
    options: [
      { key: 'size', label: 'Pixel block size', type: 'number', defaultValue: 10, min: 2, max: 80 },
    ],
  },
  {
    id: 'image-add-text',
    name: 'Add Text to Image',
    category: 'image',
    description: 'Overlay text onto an image.',
    accept: 'image/*',
    tags: ['image', 'text'],
    options: [
      { key: 'text', label: 'Text', type: 'text', defaultValue: 'TinyWow Tools' },
      { key: 'fontSize', label: 'Font size', type: 'number', defaultValue: 42, min: 8, max: 240 },
      { key: 'color', label: 'Text color', type: 'color', defaultValue: '#ffffff' },
      { key: 'x', label: 'X position', type: 'number', defaultValue: 20, min: 0 },
      { key: 'y', label: 'Y position', type: 'number', defaultValue: 60, min: 0 },
    ],
  },
  {
    id: 'image-add-border',
    name: 'Add Border',
    category: 'image',
    description: 'Add a border around an image.',
    accept: 'image/*',
    tags: ['image', 'border'],
    options: [
      { key: 'size', label: 'Border size', type: 'number', defaultValue: 16, min: 1, max: 200 },
      { key: 'color', label: 'Border color', type: 'color', defaultValue: '#0ea5e9' },
    ],
  },
  {
    id: 'image-split',
    name: 'Image Split',
    category: 'image',
    description: 'Split one image into rows and columns.',
    accept: 'image/*',
    tags: ['image', 'split'],
    options: [
      { key: 'rows', label: 'Rows', type: 'number', defaultValue: 2, min: 1, max: 10 },
      { key: 'cols', label: 'Columns', type: 'number', defaultValue: 2, min: 1, max: 10 },
    ],
  },
  {
    id: 'image-combine',
    name: 'Combine Images',
    category: 'image',
    description: 'Combine multiple images into one canvas.',
    accept: 'image/*',
    multiple: true,
    tags: ['image', 'combine'],
    options: [
      {
        key: 'direction',
        label: 'Layout direction',
        type: 'select',
        defaultValue: 'horizontal',
        options: [
          { label: 'Horizontal', value: 'horizontal' },
          { label: 'Vertical', value: 'vertical' },
        ],
      },
      { key: 'gap', label: 'Gap', type: 'number', defaultValue: 8, min: 0, max: 100 },
    ],
  },
  {
    id: 'image-collage',
    name: 'Collage Maker',
    category: 'image',
    description: 'Create a grid collage from multiple images.',
    accept: 'image/*',
    multiple: true,
    tags: ['image', 'collage'],
    options: [
      { key: 'columns', label: 'Columns', type: 'number', defaultValue: 3, min: 1, max: 8 },
      { key: 'gap', label: 'Gap', type: 'number', defaultValue: 8, min: 0, max: 50 },
      { key: 'background', label: 'Background color', type: 'color', defaultValue: '#ffffff' },
    ],
  },
  {
    id: 'image-background-transparent',
    name: 'Background Transparent',
    category: 'image',
    description: 'Make near-white background pixels transparent.',
    accept: 'image/*',
    tags: ['image', 'transparent', 'mask'],
    options: [
      { key: 'threshold', label: 'White threshold', type: 'number', defaultValue: 235, min: 0, max: 255 },
    ],
  },
  {
    id: 'image-blur-background',
    name: 'Blur Background',
    category: 'image',
    description: 'Apply a blur effect to the full image.',
    accept: 'image/*',
    tags: ['image', 'blur'],
    options: [
      { key: 'radius', label: 'Blur radius', type: 'number', defaultValue: 8, min: 1, max: 30 },
    ],
  },
  {
    id: 'png-jpg',
    name: 'PNG to JPG',
    category: 'image',
    description: 'Convert PNG images to JPG.',
    accept: '.png',
    tags: ['png', 'jpg', 'convert'],
  },
  {
    id: 'jpg-png',
    name: 'JPG to PNG',
    category: 'image',
    description: 'Convert JPG images to PNG.',
    accept: '.jpg,.jpeg',
    tags: ['jpg', 'png', 'convert'],
  },
  {
    id: 'png-webp',
    name: 'PNG to WEBP',
    category: 'image',
    description: 'Convert PNG images to WEBP.',
    accept: '.png',
    tags: ['png', 'webp', 'convert'],
  },
  {
    id: 'webp-png',
    name: 'WEBP to PNG',
    category: 'image',
    description: 'Convert WEBP images to PNG.',
    accept: '.webp',
    tags: ['webp', 'png', 'convert'],
  },
  {
    id: 'webp-jpg',
    name: 'WEBP to JPG',
    category: 'image',
    description: 'Convert WEBP images to JPG.',
    accept: '.webp',
    tags: ['webp', 'jpg', 'convert'],
  },
  {
    id: 'jpg-webp',
    name: 'JPG to WEBP',
    category: 'image',
    description: 'Convert JPG images to WEBP.',
    accept: '.jpg,.jpeg',
    tags: ['jpg', 'webp', 'convert'],
  },
  {
    id: 'gif-jpg',
    name: 'GIF to JPG',
    category: 'image',
    description: 'Convert GIF images to JPG.',
    accept: '.gif',
    tags: ['gif', 'jpg', 'convert'],
  },
  {
    id: 'gif-png',
    name: 'GIF to PNG',
    category: 'image',
    description: 'Convert GIF images to PNG.',
    accept: '.gif',
    tags: ['gif', 'png', 'convert'],
  },
  {
    id: 'tiff-jpg',
    name: 'TIFF to JPG',
    category: 'image',
    description: 'Convert TIFF images to JPG.',
    accept: '.tif,.tiff',
    tags: ['tiff', 'jpg', 'convert'],
  },
  {
    id: 'tiff-png',
    name: 'TIFF to PNG',
    category: 'image',
    description: 'Convert TIFF images to PNG.',
    accept: '.tif,.tiff',
    tags: ['tiff', 'png', 'convert'],
  },
  {
    id: 'svg-png',
    name: 'SVG to PNG',
    category: 'image',
    description: 'Convert SVG images to PNG.',
    accept: '.svg',
    tags: ['svg', 'png', 'convert'],
  },
  {
    id: 'ocr-image-to-text',
    name: 'Image to Text',
    category: 'ocr',
    description: 'Extract text from images with OCR.',
    accept: 'image/*',
    tags: ['ocr', 'text'],
    options: [
      {
        key: 'lang',
        label: 'OCR language',
        type: 'select',
        defaultValue: 'eng',
        options: [
          { label: 'English (eng)', value: 'eng' },
          { label: 'Korean + English (kor+eng)', value: 'kor+eng' },
        ],
      },
    ],
  },
  {
    id: 'ocr-pdf-to-text',
    name: 'PDF to Text',
    category: 'ocr',
    description: 'Extract visible text from a PDF.',
    accept: '.pdf',
    tags: ['ocr', 'pdf', 'text'],
  },
  {
    id: 'video-to-gif',
    name: 'Video to GIF',
    category: 'video',
    description: 'Convert videos to animated GIFs.',
    accept: 'video/*',
    tags: ['video', 'gif', 'convert'],
    options: [
      { key: 'fps', label: 'FPS', type: 'number', defaultValue: 12, min: 5, max: 30 },
      { key: 'width', label: 'Width', type: 'number', defaultValue: 480, min: 120, max: 1920 },
    ],
  },
  {
    id: 'video-to-webp',
    name: 'Video to WebP',
    category: 'video',
    description: 'Convert videos to animated WEBP files.',
    accept: 'video/*',
    tags: ['video', 'webp', 'convert'],
    options: [
      { key: 'fps', label: 'FPS', type: 'number', defaultValue: 12, min: 5, max: 30 },
      { key: 'width', label: 'Width', type: 'number', defaultValue: 640, min: 120, max: 1920 },
    ],
  },
  {
    id: 'mute-video',
    name: 'Mute Video',
    category: 'video',
    description: 'Remove the audio track from a video.',
    accept: 'video/*',
    tags: ['video', 'mute'],
  },
  {
    id: 'extract-audio',
    name: 'Extract Audio',
    category: 'video',
    description: 'Extract audio from a video file.',
    accept: 'video/*',
    tags: ['video', 'audio', 'extract'],
  },
  {
    id: 'video-compress',
    name: 'Video Compress',
    category: 'video',
    description: 'Compress video with CRF-based quality control.',
    accept: 'video/*',
    tags: ['video', 'compress'],
    options: [
      { key: 'crf', label: 'CRF (lower = better quality)', type: 'number', defaultValue: 28, min: 18, max: 40 },
    ],
  },
  {
    id: 'mp4-webm',
    name: 'MP4 to WEBM',
    category: 'video',
    description: 'Convert MP4 videos to WEBM.',
    accept: '.mp4',
    tags: ['mp4', 'webm', 'convert'],
  },
  {
    id: 'mp4-mov',
    name: 'MP4 to MOV',
    category: 'video',
    description: 'Convert MP4 videos to MOV.',
    accept: '.mp4',
    tags: ['mp4', 'mov', 'convert'],
  },
  {
    id: 'mov-mp4',
    name: 'MOV to MP4',
    category: 'video',
    description: 'Convert MOV videos to MP4.',
    accept: '.mov',
    tags: ['mov', 'mp4', 'convert'],
  },
  {
    id: 'avi-mp4',
    name: 'AVI to MP4',
    category: 'video',
    description: 'Convert AVI videos to MP4.',
    accept: '.avi',
    tags: ['avi', 'mp4', 'convert'],
  },
  {
    id: 'm4a-mp3',
    name: 'M4A to MP3',
    category: 'audio',
    description: 'Convert M4A audio files to MP3.',
    accept: '.m4a',
    tags: ['audio', 'm4a', 'mp3'],
  },
  {
    id: 'm4a-wav',
    name: 'M4A to WAV',
    category: 'audio',
    description: 'Convert M4A audio files to WAV.',
    accept: '.m4a',
    tags: ['audio', 'm4a', 'wav'],
  },
  {
    id: 'aac-mp3',
    name: 'AAC to MP3',
    category: 'audio',
    description: 'Convert AAC audio files to MP3.',
    accept: '.aac',
    tags: ['audio', 'aac', 'mp3'],
  },
  {
    id: 'webm-mp3',
    name: 'WEBM to MP3',
    category: 'audio',
    description: 'Convert WEBM audio files to MP3.',
    accept: '.webm',
    tags: ['audio', 'webm', 'mp3'],
  },
  {
    id: 'mp4-wav',
    name: 'MP4 to WAV',
    category: 'audio',
    description: 'Extract WAV audio from MP4 files.',
    accept: '.mp4',
    tags: ['audio', 'mp4', 'wav'],
  },
  {
    id: 'csv-json',
    name: 'CSV to JSON',
    category: 'file',
    description: 'Convert CSV files to JSON.',
    accept: '.csv',
    tags: ['csv', 'json'],
  },
  {
    id: 'json-csv',
    name: 'JSON to CSV',
    category: 'file',
    description: 'Convert JSON files to CSV.',
    accept: '.json',
    tags: ['json', 'csv'],
  },
  {
    id: 'excel-csv',
    name: 'Excel to CSV',
    category: 'file',
    description: 'Convert Excel spreadsheets to CSV.',
    accept: '.xls,.xlsx',
    tags: ['excel', 'csv'],
  },
  {
    id: 'csv-excel',
    name: 'CSV to Excel',
    category: 'file',
    description: 'Convert CSV files to Excel workbooks.',
    accept: '.csv',
    tags: ['csv', 'excel'],
  },
  {
    id: 'xml-json',
    name: 'XML to JSON',
    category: 'file',
    description: 'Convert XML files to JSON.',
    accept: '.xml',
    tags: ['xml', 'json'],
  },
  {
    id: 'json-xml',
    name: 'JSON to XML',
    category: 'file',
    description: 'Convert JSON files to XML.',
    accept: '.json',
    tags: ['json', 'xml'],
  },
  {
    id: 'xml-csv',
    name: 'XML to CSV',
    category: 'file',
    description: 'Convert XML data to CSV.',
    accept: '.xml',
    tags: ['xml', 'csv'],
  },
  {
    id: 'split-csv',
    name: 'Split CSV',
    category: 'file',
    description: 'Split a CSV into multiple files by row count.',
    accept: '.csv',
    tags: ['csv', 'split'],
    options: [
      { key: 'rowsPerFile', label: 'Rows per file', type: 'number', defaultValue: 1000, min: 10 },
    ],
  },
  {
    id: 'create-zip',
    name: 'Create ZIP',
    category: 'file',
    description: 'Bundle multiple files into a ZIP archive.',
    accept: '*',
    multiple: true,
    tags: ['zip', 'compress'],
  },
  {
    id: 'extract-zip',
    name: 'Extract ZIP',
    category: 'file',
    description: 'Extract files from a ZIP archive.',
    accept: '.zip',
    tags: ['zip', 'extract'],
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    category: 'web',
    description: 'Generate a QR code from text or a URL.',
    accept: '*',
    tags: ['qr', 'web'],
    options: [
      { key: 'content', label: 'QR content', type: 'text', defaultValue: 'https://example.com' },
      { key: 'size', label: 'Size (px)', type: 'number', defaultValue: 320, min: 64, max: 2048 },
    ],
  },
  {
    id: 'url-image',
    name: 'URL to Image',
    category: 'web',
    description: 'Capture readable HTML from a URL into an image.',
    accept: '*',
    tags: ['url', 'screenshot', 'image'],
    options: [
      { key: 'url', label: 'Target URL', type: 'text', defaultValue: 'https://example.com' },
      { key: 'width', label: 'Canvas width', type: 'number', defaultValue: 1200, min: 320, max: 4096 },
    ],
  },
  {
    id: 'url-pdf',
    name: 'URL to PDF',
    category: 'web',
    description: 'Capture readable HTML from a URL into a PDF.',
    accept: '*',
    tags: ['url', 'pdf', 'web'],
    options: [
      { key: 'url', label: 'Target URL', type: 'text', defaultValue: 'https://example.com' },
      { key: 'width', label: 'Canvas width', type: 'number', defaultValue: 1200, min: 320, max: 4096 },
    ],
  },
  {
    id: 'detect-cms',
    name: 'Detect CMS',
    category: 'web',
    description: 'Inspect HTML for common CMS fingerprints.',
    accept: '*',
    tags: ['cms', 'web', 'detect'],
    options: [
      { key: 'url', label: 'Target URL', type: 'text', defaultValue: 'https://example.com' },
    ],
  },
  {
    id: 'image-metadata',
    name: 'Image Metadata Viewer',
    category: 'web',
    description: 'Inspect metadata embedded in image files.',
    accept: 'image/*',
    tags: ['image', 'metadata'],
  },
];

export const categories: ToolCategoryDefinition[] = [
  {
    id: 'pdf',
    label: 'PDF Tools',
    description: 'Merge, split, reorder, convert, and optimize PDF files.',
    tools: [
      'pdf-merge',
      'pdf-split',
      'pdf-rearrange',
      'pdf-rotate',
      'pdf-delete-page',
      'pdf-add-page-numbers',
      'pdf-extract-images',
      'pdf-compress',
      'pdf-to-png',
      'pdf-to-jpg',
      'pdf-to-webp',
      'image-to-pdf',
    ],
  },
  {
    id: 'image',
    label: 'Image Tools',
    description: 'Resize, convert, edit, combine, and stylize images.',
    tools: [
      'image-resize',
      'image-compress',
      'image-crop',
      'image-flip',
      'image-rotate',
      'image-pixelate',
      'image-add-text',
      'image-add-border',
      'image-split',
      'image-combine',
      'image-collage',
      'image-background-transparent',
      'image-blur-background',
      'png-jpg',
      'jpg-png',
      'png-webp',
      'webp-png',
      'webp-jpg',
      'jpg-webp',
      'gif-jpg',
      'gif-png',
      'tiff-jpg',
      'tiff-png',
      'svg-png',
    ],
  },
  {
    id: 'ocr',
    label: 'OCR Tools',
    description: 'Extract visible text from images and PDFs.',
    tools: ['ocr-image-to-text', 'ocr-pdf-to-text'],
  },
  {
    id: 'video',
    label: 'Video Tools',
    description: 'Convert, compress, mute, and extract media from video files.',
    tools: [
      'video-to-gif',
      'video-to-webp',
      'mute-video',
      'extract-audio',
      'video-compress',
      'mp4-webm',
      'mp4-mov',
      'mov-mp4',
      'avi-mp4',
    ],
  },
  {
    id: 'audio',
    label: 'Audio Tools',
    description: 'Convert between popular audio formats.',
    tools: ['m4a-mp3', 'm4a-wav', 'aac-mp3', 'webm-mp3', 'mp4-wav'],
  },
  {
    id: 'file',
    label: 'File and Data Tools',
    description: 'Convert structured data, split CSV files, and work with ZIP archives.',
    tools: [
      'csv-json',
      'json-csv',
      'excel-csv',
      'csv-excel',
      'xml-json',
      'json-xml',
      'xml-csv',
      'split-csv',
      'create-zip',
      'extract-zip',
    ],
  },
  {
    id: 'web',
    label: 'Web Tools',
    description: 'Generate QR codes, capture URLs, detect CMS signatures, and inspect image metadata.',
    tools: ['qr-generator', 'url-image', 'url-pdf', 'detect-cms', 'image-metadata'],
  },
];

const toolById = new Map(tools.map((tool) => [tool.id, tool]));

export function getToolById(toolId: string): ToolDefinition | undefined {
  return toolById.get(toolId);
}

export function getToolsByCategory(categoryId: string): ToolDefinition[] {
  return tools.filter((tool) => tool.category === categoryId);
}
