import { ToolCategoryDefinition, ToolDefinition } from '@/types/tool';

export const tools: ToolDefinition[] = [
  {
    id: 'pdf-merge',
    name: 'PDF Merge',
    category: 'pdf',
    description: 'Combine multiple PDF files into one document.',
    accept: '.pdf',
    multiple: true,
    tags: ['pdf', 'merge', 'combine'],
    browseGroups: ['popular', 'merge', 'editor-enabled'],
    previewKind: 'pdf-merge',
  },
  {
    id: 'pdf-split',
    name: 'PDF Split',
    category: 'pdf',
    description: 'Split a PDF into one file per page.',
    accept: '.pdf',
    tags: ['pdf', 'split'],
  },
  {
    id: 'pdf-rearrange',
    name: 'PDF Rearrange',
    category: 'pdf',
    description: 'Reorder PDF pages by page number.',
    accept: '.pdf',
    tags: ['pdf', 'reorder'],
    browseGroups: ['merge', 'editor-enabled'],
    previewKind: 'pdf-merge',
    options: [
      {
        key: 'order',
        label: 'Page order',
        type: 'text',
        defaultValue: '',
        placeholder: 'e.g. 3,1,2',
      },
    ],
  },
  {
    id: 'pdf-rotate',
    name: 'PDF Rotate',
    category: 'pdf',
    description: 'Rotate every page in a PDF.',
    accept: '.pdf',
    tags: ['pdf', 'rotate'],
    options: [
      {
        key: 'degrees',
        label: 'Rotation',
        type: 'select',
        defaultValue: 90,
        options: [
          { label: '90 degrees', value: 90 },
          { label: '180 degrees', value: 180 },
          { label: '270 degrees', value: 270 },
        ],
      },
    ],
  },
  {
    id: 'pdf-delete-page',
    name: 'PDF Delete Page',
    category: 'pdf',
    description: 'Remove selected pages from a PDF.',
    accept: '.pdf',
    tags: ['pdf', 'delete'],
    browseGroups: ['trim'],
    options: [
      {
        key: 'pages',
        label: 'Pages to delete',
        type: 'text',
        defaultValue: '',
        placeholder: 'e.g. 2,5',
      },
    ],
  },
  {
    id: 'pdf-add-page-numbers',
    name: 'PDF Page Number',
    category: 'pdf',
    description: 'Insert automatic page numbers into a PDF.',
    accept: '.pdf',
    tags: ['pdf', 'numbering', 'pages'],
    browseGroups: ['new'],
    options: [
      {
        key: 'startNumber',
        label: 'Start number',
        type: 'number',
        defaultValue: 1,
        min: 1,
      },
      {
        key: 'fontSize',
        label: 'Font size',
        type: 'number',
        defaultValue: 12,
        min: 8,
        max: 72,
      },
    ],
  },
  {
    id: 'pdf-watermark',
    name: 'PDF Watermark',
    category: 'pdf',
    description: 'Overlay text or an image watermark across each PDF page.',
    accept: '.pdf,.png,.jpg,.jpeg,.webp',
    multiple: true,
    tags: ['pdf', 'watermark', 'stamp'],
    browseGroups: ['new'],
    options: [
      {
        key: 'watermarkType',
        label: 'Watermark type',
        type: 'select',
        defaultValue: 'text',
        options: [
          { label: 'Text', value: 'text' },
          { label: 'Image', value: 'image' },
        ],
      },
      {
        key: 'text',
        label: 'Text',
        type: 'text',
        defaultValue: 'JH Toolbox',
      },
      {
        key: 'fontSize',
        label: 'Font size',
        type: 'number',
        defaultValue: 32,
        min: 8,
        max: 160,
      },
      {
        key: 'opacity',
        label: 'Opacity',
        type: 'range',
        defaultValue: 0.2,
        min: 0.05,
        max: 1,
        step: 0.05,
      },
      {
        key: 'rotation',
        label: 'Rotation',
        type: 'number',
        defaultValue: -24,
        min: -180,
        max: 180,
      },
      {
        key: 'scale',
        label: 'Scale',
        type: 'range',
        defaultValue: 0.24,
        min: 0.05,
        max: 1,
        step: 0.02,
      },
    ],
  },
  {
    id: 'pdf-redact',
    name: 'PDF Redact',
    category: 'pdf',
    description: 'Cover a fixed rectangle on selected PDF pages with a solid redact box.',
    accept: '.pdf',
    tags: ['pdf', 'redact', 'cover'],
    browseGroups: ['trim'],
    options: [
      { key: 'pageStart', label: 'Start page', type: 'number', defaultValue: 1, min: 1 },
      { key: 'pageEnd', label: 'End page', type: 'number', defaultValue: 1, min: 1 },
      { key: 'x', label: 'X', type: 'number', defaultValue: 40, min: 0 },
      { key: 'y', label: 'Y', type: 'number', defaultValue: 40, min: 0 },
      { key: 'width', label: 'Width', type: 'number', defaultValue: 240, min: 1 },
      { key: 'height', label: 'Height', type: 'number', defaultValue: 48, min: 1 },
      { key: 'color', label: 'Redact color', type: 'color', defaultValue: '#000000' },
    ],
  },
  {
    id: 'pdf-extract-images',
    name: 'PDF Extract Images',
    category: 'pdf',
    description: 'Render each PDF page as a PNG image.',
    accept: '.pdf',
    tags: ['pdf', 'extract', 'images'],
  },
  {
    id: 'pdf-compress',
    name: 'PDF Compress',
    category: 'pdf',
    description: 'Re-save a PDF with compact object streams.',
    accept: '.pdf',
    tags: ['pdf', 'compress'],
    browseGroups: ['compress'],
  },
  {
    id: 'pdf-to-png',
    name: 'PDF to PNG',
    category: 'pdf',
    description: 'Convert PDF pages to PNG images.',
    accept: '.pdf',
    tags: ['pdf', 'png', 'convert'],
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    category: 'pdf',
    description: 'Convert PDF pages to JPG images.',
    accept: '.pdf',
    tags: ['pdf', 'jpg', 'convert'],
    options: [
      {
        key: 'quality',
        label: 'JPG quality',
        type: 'range',
        defaultValue: 0.85,
        min: 0.3,
        max: 1,
        step: 0.05,
      },
    ],
  },
  {
    id: 'pdf-to-webp',
    name: 'PDF to WEBP',
    category: 'pdf',
    description: 'Convert PDF pages to WEBP images.',
    accept: '.pdf',
    tags: ['pdf', 'webp', 'convert'],
    options: [
      {
        key: 'quality',
        label: 'WEBP quality',
        type: 'range',
        defaultValue: 0.85,
        min: 0.3,
        max: 1,
        step: 0.05,
      },
    ],
  },
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    category: 'pdf',
    description: 'Combine multiple images into a single PDF.',
    accept: '.png,.jpg,.jpeg,.webp,.gif,.tif,.tiff',
    multiple: true,
    tags: ['image', 'pdf', 'convert'],
  },
  {
    id: 'image-resize',
    name: 'Resize Image',
    category: 'image',
    description: 'Resize images to a target width and height.',
    accept: 'image/*',
    tags: ['image', 'resize'],
    browseGroups: ['editor-enabled'],
    previewKind: 'image',
    options: [
      { key: 'width', label: 'Width', type: 'number', defaultValue: 1280, min: 16 },
      { key: 'height', label: 'Height', type: 'number', defaultValue: 720, min: 16 },
      {
        key: 'format',
        label: 'Output format',
        type: 'select',
        defaultValue: 'image/png',
        options: [
          { label: 'PNG', value: 'image/png' },
          { label: 'JPG', value: 'image/jpeg' },
          { label: 'WEBP', value: 'image/webp' },
        ],
      },
    ],
  },
  {
    id: 'image-compress',
    name: 'Compress Image',
    category: 'image',
    description: 'Reduce image file size with quality control.',
    accept: 'image/*',
    tags: ['image', 'compress'],
    browseGroups: ['popular', 'compress', 'editor-enabled'],
    previewKind: 'image',
    options: [
      {
        key: 'quality',
        label: 'Quality',
        type: 'range',
        defaultValue: 0.75,
        min: 0.2,
        max: 1,
        step: 0.05,
      },
      {
        key: 'format',
        label: 'Output format',
        type: 'select',
        defaultValue: 'image/jpeg',
        options: [
          { label: 'JPG', value: 'image/jpeg' },
          { label: 'WEBP', value: 'image/webp' },
          { label: 'PNG', value: 'image/png' },
        ],
      },
    ],
  },
  {
    id: 'image-crop',
    name: 'Crop Image',
    category: 'image',
    description: 'Crop images to an exact rectangle.',
    accept: 'image/*',
    tags: ['image', 'crop'],
    browseGroups: ['editor-enabled', 'trim'],
    previewKind: 'image',
    options: [
      { key: 'x', label: 'X', type: 'number', defaultValue: 0, min: 0 },
      { key: 'y', label: 'Y', type: 'number', defaultValue: 0, min: 0 },
      { key: 'width', label: 'Width', type: 'number', defaultValue: 512, min: 1 },
      { key: 'height', label: 'Height', type: 'number', defaultValue: 512, min: 1 },
    ],
  },
  {
    id: 'image-flip',
    name: 'Flip Image',
    category: 'image',
    description: 'Flip images horizontally or vertically.',
    accept: 'image/*',
    tags: ['image', 'flip'],
    options: [
      { key: 'horizontal', label: 'Flip horizontally', type: 'checkbox', defaultValue: true },
      { key: 'vertical', label: 'Flip vertically', type: 'checkbox', defaultValue: false },
    ],
  },
  {
    id: 'image-rotate',
    name: 'Rotate Image',
    category: 'image',
    description: 'Rotate images by a custom angle.',
    accept: 'image/*',
    tags: ['image', 'rotate'],
    options: [
      { key: 'degrees', label: 'Rotation', type: 'number', defaultValue: 90, min: 0, max: 360 },
    ],
  },
  {
    id: 'image-pixelate',
    name: 'Pixelate Image',
    category: 'image',
    description: 'Apply a pixelation effect to images.',
    accept: 'image/*',
    tags: ['image', 'pixelate'],
    options: [
      { key: 'size', label: 'Pixel block size', type: 'number', defaultValue: 10, min: 2, max: 80 },
    ],
  },
  {
    id: 'image-add-text',
    name: 'Add Text to Image',
    category: 'image',
    description: 'Overlay text onto an image.',
    accept: 'image/*',
    tags: ['image', 'text'],
    options: [
      { key: 'text', label: 'Text', type: 'text', defaultValue: 'TinyWow Tools' },
      { key: 'fontSize', label: 'Font size', type: 'number', defaultValue: 42, min: 8, max: 240 },
      { key: 'color', label: 'Text color', type: 'color', defaultValue: '#ffffff' },
      { key: 'x', label: 'X position', type: 'number', defaultValue: 20, min: 0 },
      { key: 'y', label: 'Y position', type: 'number', defaultValue: 60, min: 0 },
    ],
  },
  {
    id: 'image-add-border',
    name: 'Add Border',
    category: 'image',
    description: 'Add a border around an image.',
    accept: 'image/*',
    tags: ['image', 'border'],
    options: [
      { key: 'size', label: 'Border size', type: 'number', defaultValue: 16, min: 1, max: 200 },
      { key: 'color', label: 'Border color', type: 'color', defaultValue: '#0ea5e9' },
    ],
  },
  {
    id: 'image-split',
    name: 'Image Split',
    category: 'image',
    description: 'Split one image into rows and columns.',
    accept: 'image/*',
    tags: ['image', 'split'],
    options: [
      { key: 'rows', label: 'Rows', type: 'number', defaultValue: 2, min: 1, max: 10 },
      { key: 'cols', label: 'Columns', type: 'number', defaultValue: 2, min: 1, max: 10 },
    ],
  },
  {
    id: 'image-combine',
    name: 'Combine Images',
    category: 'image',
    description: 'Combine multiple images into one canvas.',
    accept: 'image/*',
    multiple: true,
    tags: ['image', 'combine'],
    options: [
      {
        key: 'direction',
        label: 'Layout direction',
        type: 'select',
        defaultValue: 'horizontal',
        options: [
          { label: 'Horizontal', value: 'horizontal' },
          { label: 'Vertical', value: 'vertical' },
        ],
      },
      { key: 'gap', label: 'Gap', type: 'number', defaultValue: 8, min: 0, max: 100 },
    ],
  },
  {
    id: 'image-collage',
    name: 'Collage Maker',
    category: 'image',
    description: 'Create a grid collage from multiple images.',
    accept: 'image/*',
    multiple: true,
    tags: ['image', 'collage'],
    options: [
      { key: 'columns', label: 'Columns', type: 'number', defaultValue: 3, min: 1, max: 8 },
      { key: 'gap', label: 'Gap', type: 'number', defaultValue: 8, min: 0, max: 50 },
      { key: 'background', label: 'Background color', type: 'color', defaultValue: '#ffffff' },
    ],
  },
  {
    id: 'image-background-transparent',
    name: 'Background Remove',
    category: 'image',
    description: 'Remove a light or solid background and export a transparent PNG.',
    accept: 'image/*',
    tags: ['image', 'transparent', 'mask', 'background'],
    browseGroups: ['new', 'editor-enabled'],
    previewKind: 'image',
    options: [
      { key: 'threshold', label: 'Background threshold', type: 'number', defaultValue: 42, min: 5, max: 180 },
    ],
  },
  {
    id: 'image-blur-background',
    name: 'Blur Image',
    category: 'image',
    description: 'Apply a blur effect across the full image.',
    accept: 'image/*',
    tags: ['image', 'blur'],
    browseGroups: ['editor-enabled'],
    previewKind: 'image',
    options: [
      { key: 'radius', label: 'Blur radius', type: 'number', defaultValue: 8, min: 1, max: 30 },
    ],
  },
  {
    id: 'image-upscale',
    name: 'Image Upscale',
    category: 'image',
    description: 'Scale an image up with high-quality browser resizing.',
    accept: 'image/*',
    tags: ['image', 'upscale', 'resize'],
    browseGroups: ['new', 'editor-enabled'],
    previewKind: 'image',
    options: [
      {
        key: 'scale',
        label: 'Scale',
        type: 'select',
        defaultValue: 2,
        options: [
          { label: '2x', value: 2 },
          { label: '3x', value: 3 },
          { label: '4x', value: 4 },
        ],
      },
      {
        key: 'format',
        label: 'Output format',
        type: 'select',
        defaultValue: 'image/png',
        options: [
          { label: 'PNG', value: 'image/png' },
          { label: 'JPG', value: 'image/jpeg' },
          { label: 'WEBP', value: 'image/webp' },
        ],
      },
    ],
  },
  {
    id: 'image-watermark',
    name: 'Image Watermark',
    category: 'image',
    description: 'Overlay text or a second image as a watermark.',
    accept: 'image/*',
    multiple: true,
    tags: ['image', 'watermark', 'stamp'],
    browseGroups: ['new', 'editor-enabled'],
    previewKind: 'image',
    options: [
      {
        key: 'watermarkType',
        label: 'Watermark type',
        type: 'select',
        defaultValue: 'text',
        options: [
          { label: 'Text', value: 'text' },
          { label: 'Image', value: 'image' },
        ],
      },
      { key: 'text', label: 'Text', type: 'text', defaultValue: 'JH Toolbox' },
      { key: 'fontSize', label: 'Font size', type: 'number', defaultValue: 42, min: 8, max: 240 },
      { key: 'color', label: 'Text color', type: 'color', defaultValue: '#ffffff' },
      { key: 'opacity', label: 'Opacity', type: 'range', defaultValue: 0.5, min: 0.05, max: 1, step: 0.05 },
      { key: 'scale', label: 'Scale', type: 'range', defaultValue: 0.24, min: 0.08, max: 1, step: 0.02 },
      { key: 'x', label: 'X', type: 'number', defaultValue: 20, min: 0 },
      { key: 'y', label: 'Y', type: 'number', defaultValue: 20, min: 0 },
    ],
  },
  {
    id: 'image-color-palette-extract',
    name: 'Image Color Palette Extract',
    category: 'image',
    description: 'Extract the dominant colors from an image and generate palette swatches.',
    accept: 'image/*',
    tags: ['image', 'palette', 'colors'],
    browseGroups: ['new', 'editor-enabled'],
    previewKind: 'image',
    options: [{ key: 'count', label: 'Color count', type: 'number', defaultValue: 6, min: 3, max: 12 }],
  },
  {
    id: 'image-auto-enhance',
    name: 'Image Auto Enhance',
    category: 'image',
    description: 'Auto-adjust brightness, contrast, and clarity for a cleaner result.',
    accept: 'image/*',
    tags: ['image', 'enhance', 'contrast'],
    browseGroups: ['new', 'editor-enabled'],
    previewKind: 'image',
    options: [
      { key: 'strength', label: 'Strength', type: 'range', defaultValue: 0.75, min: 0.1, max: 1.5, step: 0.05 },
      {
        key: 'format',
        label: 'Output format',
        type: 'select',
        defaultValue: 'image/jpeg',
        options: [
          { label: 'JPG', value: 'image/jpeg' },
          { label: 'PNG', value: 'image/png' },
          { label: 'WEBP', value: 'image/webp' },
        ],
      },
    ],
  },
  {
    id: 'png-jpg',
    name: 'PNG to JPG',
    category: 'image',
    description: 'Convert PNG images to JPG.',
    accept: '.png',
    tags: ['png', 'jpg', 'convert'],
  },
  {
    id: 'jpg-png',
    name: 'JPG to PNG',
    category: 'image',
    description: 'Convert JPG images to PNG.',
    accept: '.jpg,.jpeg',
    tags: ['jpg', 'png', 'convert'],
  },
  {
    id: 'png-webp',
    name: 'PNG to WEBP',
    category: 'image',
    description: 'Convert PNG images to WEBP.',
    accept: '.png',
    tags: ['png', 'webp', 'convert'],
  },
  {
    id: 'webp-png',
    name: 'WEBP to PNG',
    category: 'image',
    description: 'Convert WEBP images to PNG.',
    accept: '.webp',
    tags: ['webp', 'png', 'convert'],
  },
  {
    id: 'webp-jpg',
    name: 'WEBP to JPG',
    category: 'image',
    description: 'Convert WEBP images to JPG.',
    accept: '.webp',
    tags: ['webp', 'jpg', 'convert'],
  },
  {
    id: 'jpg-webp',
    name: 'JPG to WEBP',
    category: 'image',
    description: 'Convert JPG images to WEBP.',
    accept: '.jpg,.jpeg',
    tags: ['jpg', 'webp', 'convert'],
  },
  {
    id: 'gif-jpg',
    name: 'GIF to JPG',
    category: 'image',
    description: 'Convert GIF images to JPG.',
    accept: '.gif',
    tags: ['gif', 'jpg', 'convert'],
  },
  {
    id: 'gif-png',
    name: 'GIF to PNG',
    category: 'image',
    description: 'Convert GIF images to PNG.',
    accept: '.gif',
    tags: ['gif', 'png', 'convert'],
  },
  {
    id: 'tiff-jpg',
    name: 'TIFF to JPG',
    category: 'image',
    description: 'Convert TIFF images to JPG.',
    accept: '.tif,.tiff',
    tags: ['tiff', 'jpg', 'convert'],
  },
  {
    id: 'tiff-png',
    name: 'TIFF to PNG',
    category: 'image',
    description: 'Convert TIFF images to PNG.',
    accept: '.tif,.tiff',
    tags: ['tiff', 'png', 'convert'],
  },
  {
    id: 'svg-png',
    name: 'SVG to PNG',
    category: 'image',
    description: 'Convert SVG images to PNG.',
    accept: '.svg',
    tags: ['svg', 'png', 'convert'],
  },
  {
    id: 'ocr-image-to-text',
    name: 'Image to Text',
    category: 'ocr',
    description: 'Extract text from images with OCR.',
    accept: 'image/*',
    tags: ['ocr', 'text'],
    options: [
      {
        key: 'lang',
        label: 'OCR language',
        type: 'select',
        defaultValue: 'eng',
        options: [
          { label: 'English (eng)', value: 'eng' },
          { label: 'Korean + English (kor+eng)', value: 'kor+eng' },
        ],
      },
    ],
  },
  {
    id: 'ocr-pdf-to-text',
    name: 'PDF to Text',
    category: 'ocr',
    description: 'Extract visible text from a PDF.',
    accept: '.pdf',
    tags: ['ocr', 'pdf', 'text'],
  },
  {
    id: 'video-to-gif',
    name: 'Video to GIF',
    category: 'video',
    description: 'Convert videos to animated GIFs.',
    accept: 'video/*',
    tags: ['video', 'gif', 'convert'],
    browseGroups: ['popular', 'convert', 'capture', 'editor-enabled'],
    previewKind: 'video',
    hiddenFromBrowse: true,
    options: [
      { key: 'fps', label: 'FPS', type: 'number', defaultValue: 12, min: 5, max: 30 },
      { key: 'width', label: 'Width', type: 'number', defaultValue: 480, min: 120, max: 1920 },
    ],
  },
  {
    id: 'video-to-webp',
    name: 'Video to WebP',
    category: 'video',
    description: 'Convert videos to animated WEBP files.',
    accept: 'video/*',
    tags: ['video', 'webp', 'convert'],
    browseGroups: ['convert', 'capture', 'editor-enabled'],
    previewKind: 'video',
    hiddenFromBrowse: true,
    options: [
      { key: 'fps', label: 'FPS', type: 'number', defaultValue: 12, min: 5, max: 30 },
      { key: 'width', label: 'Width', type: 'number', defaultValue: 640, min: 120, max: 1920 },
    ],
  },
  {
    id: 'mute-video',
    name: 'Mute Video',
    category: 'video',
    description: 'Remove the audio track from a video.',
    accept: 'video/*',
    tags: ['video', 'mute'],
  },
  {
    id: 'extract-audio',
    name: 'Extract Audio',
    category: 'video',
    description: 'Extract audio from a video file.',
    accept: 'video/*',
    tags: ['video', 'audio', 'extract'],
  },
  {
    id: 'video-compress',
    name: 'Video Compress',
    category: 'video',
    description: 'Compress video with CRF-based quality control.',
    accept: 'video/*',
    tags: ['video', 'compress'],
    browseGroups: ['compress'],
    previewKind: 'video',
    options: [
      { key: 'crf', label: 'CRF (lower = better quality)', type: 'number', defaultValue: 28, min: 18, max: 40 },
    ],
  },
  {
    id: 'video-speed-change',
    name: 'Video Speed Change',
    category: 'video',
    description: 'Change playback speed for a video file.',
    accept: 'video/*',
    tags: ['video', 'speed', 'tempo'],
    browseGroups: ['new', 'editor-enabled'],
    previewKind: 'video',
    options: [
      {
        key: 'speed',
        label: 'Speed',
        type: 'select',
        defaultValue: '1.25',
        options: [
          { label: '0.5x', value: '0.5' },
          { label: '0.75x', value: '0.75' },
          { label: '1.25x', value: '1.25' },
          { label: '1.5x', value: '1.5' },
          { label: '2x', value: '2' },
        ],
      },
    ],
  },
  {
    id: 'video-crop',
    name: 'Video Crop',
    category: 'video',
    description: 'Crop a video to a target rectangle.',
    accept: 'video/*',
    tags: ['video', 'crop', 'trim'],
    browseGroups: ['new', 'trim', 'editor-enabled'],
    previewKind: 'video',
    options: [
      { key: 'x', label: 'X', type: 'number', defaultValue: 0, min: 0 },
      { key: 'y', label: 'Y', type: 'number', defaultValue: 0, min: 0 },
      { key: 'width', label: 'Width', type: 'number', defaultValue: 1280, min: 16 },
      { key: 'height', label: 'Height', type: 'number', defaultValue: 720, min: 16 },
    ],
  },
  {
    id: 'video-resize',
    name: 'Video Resize',
    category: 'video',
    description: 'Resize video resolution to a specific width and height.',
    accept: 'video/*',
    tags: ['video', 'resize', 'scale'],
    browseGroups: ['new', 'editor-enabled'],
    previewKind: 'video',
    options: [
      { key: 'width', label: 'Width', type: 'number', defaultValue: 1280, min: 120 },
      { key: 'height', label: 'Height', type: 'number', defaultValue: 720, min: 120 },
    ],
  },
  {
    id: 'video-watermark',
    name: 'Video Watermark',
    category: 'video',
    description: 'Overlay text or an image watermark on a video.',
    accept: 'video/*,.png,.jpg,.jpeg,.webp',
    multiple: true,
    tags: ['video', 'watermark', 'overlay'],
    browseGroups: ['new', 'editor-enabled'],
    previewKind: 'video',
    options: [
      {
        key: 'watermarkType',
        label: 'Watermark type',
        type: 'select',
        defaultValue: 'text',
        options: [
          { label: 'Text', value: 'text' },
          { label: 'Image', value: 'image' },
        ],
      },
      { key: 'text', label: 'Text', type: 'text', defaultValue: 'JH Toolbox' },
      { key: 'fontSize', label: 'Font size', type: 'number', defaultValue: 42, min: 8, max: 240 },
      { key: 'opacity', label: 'Opacity', type: 'range', defaultValue: 0.6, min: 0.05, max: 1, step: 0.05 },
      { key: 'scale', label: 'Scale', type: 'range', defaultValue: 0.24, min: 0.05, max: 1, step: 0.02 },
      { key: 'x', label: 'X', type: 'number', defaultValue: 24, min: 0 },
      { key: 'y', label: 'Y', type: 'number', defaultValue: 24, min: 0 },
    ],
  },
  {
    id: 'video-reverse',
    name: 'Video Reverse',
    category: 'video',
    description: 'Reverse video playback and audio when available.',
    accept: 'video/*',
    tags: ['video', 'reverse'],
    browseGroups: ['new'],
    previewKind: 'video',
  },
  {
    id: 'video-thumbnail-generator',
    name: 'Video Thumbnail Generator',
    category: 'video',
    description: 'Generate a thumbnail image from a video timestamp.',
    accept: 'video/*',
    tags: ['video', 'thumbnail', 'capture'],
    browseGroups: ['new', 'capture', 'editor-enabled'],
    previewKind: 'video',
    options: [
      { key: 'timestamp', label: 'Timestamp', type: 'number', defaultValue: 1, min: 0 },
      {
        key: 'format',
        label: 'Output format',
        type: 'select',
        defaultValue: 'jpg',
        options: [
          { label: 'JPG', value: 'jpg' },
          { label: 'PNG', value: 'png' },
        ],
      },
      { key: 'width', label: 'Width', type: 'number', defaultValue: 960, min: 120, max: 3840 },
    ],
  },
  {
    id: 'video-convert',
    name: 'Video Converter',
    category: 'video',
    description: 'Convert videos and GIFs into MP4, WEBM, MOV, GIF, or animated WEBP in one workflow.',
    accept: '.mp4,.webm,.mov,.avi,.m4v,.mkv,.gif',
    multiple: true,
    tags: ['video', 'gif', 'convert', 'mp4', 'webm', 'mov', 'webp'],
    browseGroups: ['popular', 'convert'],
    previewKind: 'image',
    options: [
      {
        key: 'outputFormat',
        label: 'Output format',
        type: 'select',
        defaultValue: 'mp4',
        options: [
          { label: 'MP4', value: 'mp4' },
          { label: 'WEBM', value: 'webm' },
          { label: 'MOV', value: 'mov' },
          { label: 'GIF', value: 'gif' },
          { label: 'Animated WEBP', value: 'webp' },
        ],
      },
      { key: 'fps', label: 'FPS', type: 'number', defaultValue: 12, min: 5, max: 30 },
      { key: 'width', label: 'Width', type: 'number', defaultValue: 640, min: 120, max: 1920 },
    ],
  },
  {
    id: 'images-to-gif',
    name: 'Images to GIF',
    category: 'video',
    description: 'Build an animated GIF from multiple images.',
    accept: 'image/*',
    multiple: true,
    tags: ['gif', 'image', 'animation'],
    browseGroups: ['new', 'capture'],
    previewKind: 'image',
    options: [
      { key: 'fps', label: 'FPS', type: 'number', defaultValue: 4, min: 1, max: 24 },
      { key: 'width', label: 'Width', type: 'number', defaultValue: 640, min: 120, max: 1920 },
    ],
  },
  {
    id: 'gif-to-video',
    name: 'GIF to Video',
    category: 'video',
    description: 'Convert an animated GIF to MP4.',
    accept: '.gif',
    tags: ['gif', 'video', 'convert'],
    browseGroups: ['new', 'convert'],
    previewKind: 'image',
    hiddenFromBrowse: true,
  },
  {
    id: 'gif-speed-change',
    name: 'GIF Speed Change',
    category: 'video',
    description: 'Adjust GIF playback speed.',
    accept: '.gif',
    tags: ['gif', 'speed'],
    browseGroups: ['new'],
    previewKind: 'image',
    options: [
      {
        key: 'speed',
        label: 'Speed',
        type: 'select',
        defaultValue: '1.5',
        options: [
          { label: '0.5x', value: '0.5' },
          { label: '0.75x', value: '0.75' },
          { label: '1.25x', value: '1.25' },
          { label: '1.5x', value: '1.5' },
          { label: '2x', value: '2' },
        ],
      },
    ],
  },
  {
    id: 'gif-reverse',
    name: 'GIF Reverse',
    category: 'video',
    description: 'Reverse an animated GIF.',
    accept: '.gif',
    tags: ['gif', 'reverse'],
    browseGroups: ['new'],
    previewKind: 'image',
  },
  {
    id: 'gif-frame-extract',
    name: 'GIF Frame Extract',
    category: 'video',
    description: 'Extract every frame from a GIF as PNG images.',
    accept: '.gif',
    tags: ['gif', 'frames', 'extract'],
    browseGroups: ['new', 'capture'],
    previewKind: 'image',
  },
  {
    id: 'mp4-webm',
    name: 'MP4 to WEBM',
    category: 'video',
    description: 'Convert MP4 videos to WEBM.',
    accept: '.mp4',
    tags: ['mp4', 'webm', 'convert'],
    hiddenFromBrowse: true,
  },
  {
    id: 'mp4-mov',
    name: 'MP4 to MOV',
    category: 'video',
    description: 'Convert MP4 videos to MOV.',
    accept: '.mp4',
    tags: ['mp4', 'mov', 'convert'],
    hiddenFromBrowse: true,
  },
  {
    id: 'mov-mp4',
    name: 'MOV to MP4',
    category: 'video',
    description: 'Convert MOV videos to MP4.',
    accept: '.mov',
    tags: ['mov', 'mp4', 'convert'],
    hiddenFromBrowse: true,
  },
  {
    id: 'avi-mp4',
    name: 'AVI to MP4',
    category: 'video',
    description: 'Convert AVI videos to MP4.',
    accept: '.avi',
    tags: ['avi', 'mp4', 'convert'],
    hiddenFromBrowse: true,
  },
  {
    id: 'audio-convert',
    name: 'Audio Converter',
    category: 'audio',
    description: 'Convert audio files to MP3, WAV, M4A, or AAC in one workflow.',
    accept: '.mp3,.wav,.m4a,.aac,.webm,.mp4,.ogg,.flac',
    multiple: true,
    tags: ['audio', 'convert', 'mp3', 'wav', 'm4a', 'aac'],
    browseGroups: ['popular', 'convert'],
    previewKind: 'audio',
    options: [
      {
        key: 'outputFormat',
        label: 'Output format',
        type: 'select',
        defaultValue: 'mp3',
        options: [
          { label: 'MP3', value: 'mp3' },
          { label: 'WAV', value: 'wav' },
          { label: 'M4A', value: 'm4a' },
          { label: 'AAC', value: 'aac' },
        ],
      },
      {
        key: 'bitrate',
        label: 'Bitrate',
        type: 'select',
        defaultValue: '192k',
        options: [
          { label: '128 kbps', value: '128k' },
          { label: '192 kbps', value: '192k' },
          { label: '256 kbps', value: '256k' },
        ],
      },
      {
        key: 'sampleRate',
        label: 'Sample rate',
        type: 'select',
        defaultValue: 'keep',
        options: [
          { label: 'Keep original', value: 'keep' },
          { label: '44.1 kHz', value: '44100' },
          { label: '48 kHz', value: '48000' },
        ],
      },
      {
        key: 'channels',
        label: 'Channels',
        type: 'select',
        defaultValue: 'keep',
        options: [
          { label: 'Keep original', value: 'keep' },
          { label: 'Mono', value: '1' },
          { label: 'Stereo', value: '2' },
        ],
      },
    ],
  },
  {
    id: 'audio-cut',
    name: 'Audio Cutter',
    category: 'audio',
    description: 'Trim audio with a waveform editor and export the selected result.',
    accept: '.mp3,.wav,.m4a,.aac,.webm,.ogg,.flac',
    tags: ['audio', 'trim', 'cut', 'waveform'],
    browseGroups: ['popular', 'new', 'trim', 'editor-enabled'],
    previewKind: 'audio-editor',
    options: [
      {
        key: 'trimMode',
        label: 'Selection mode',
        type: 'select',
        defaultValue: 'keep',
        options: [
          { label: 'Keep selection', value: 'keep' },
          { label: 'Remove selection', value: 'remove' },
        ],
      },
      {
        key: 'outputFormat',
        label: 'Output format',
        type: 'select',
        defaultValue: 'keep',
        options: [
          { label: 'Keep original', value: 'keep' },
          { label: 'MP3', value: 'mp3' },
          { label: 'WAV', value: 'wav' },
        ],
      },
    ],
  },
  {
    id: 'audio-merge',
    name: 'Audio Merge',
    category: 'audio',
    description: 'Combine multiple audio files into a single export.',
    accept: '.mp3,.wav,.m4a,.aac,.webm,.ogg,.flac',
    multiple: true,
    tags: ['audio', 'merge', 'combine'],
    browseGroups: ['new', 'merge'],
    previewKind: 'audio',
    options: [
      {
        key: 'outputFormat',
        label: 'Output format',
        type: 'select',
        defaultValue: 'mp3',
        options: [
          { label: 'MP3', value: 'mp3' },
          { label: 'WAV', value: 'wav' },
          { label: 'M4A', value: 'm4a' },
          { label: 'AAC', value: 'aac' },
        ],
      },
    ],
  },
  {
    id: 'audio-fade',
    name: 'Audio Fade In / Fade Out',
    category: 'audio',
    description: 'Apply smooth fade-in and fade-out envelopes to audio.',
    accept: '.mp3,.wav,.m4a,.aac,.webm,.ogg,.flac',
    tags: ['audio', 'fade', 'volume'],
    browseGroups: ['new', 'editor-enabled'],
    previewKind: 'audio',
    options: [
      { key: 'fadeInDuration', label: 'Fade in duration', type: 'number', defaultValue: 1.5, min: 0, max: 30, step: 0.1 },
      { key: 'fadeOutDuration', label: 'Fade out duration', type: 'number', defaultValue: 1.5, min: 0, max: 30, step: 0.1 },
      {
        key: 'outputFormat',
        label: 'Output format',
        type: 'select',
        defaultValue: 'mp3',
        options: [
          { label: 'MP3', value: 'mp3' },
          { label: 'WAV', value: 'wav' },
          { label: 'M4A', value: 'm4a' },
          { label: 'AAC', value: 'aac' },
        ],
      },
    ],
  },
  {
    id: 'audio-speed-change',
    name: 'Audio Speed Change',
    category: 'audio',
    description: 'Change playback speed while keeping audio pitch stable.',
    accept: '.mp3,.wav,.m4a,.aac,.webm,.ogg,.flac',
    tags: ['audio', 'speed', 'tempo'],
    browseGroups: ['new', 'editor-enabled'],
    previewKind: 'audio',
    options: [
      {
        key: 'speed',
        label: 'Speed',
        type: 'select',
        defaultValue: '1.25',
        options: [
          { label: '0.5x', value: '0.5' },
          { label: '0.75x', value: '0.75' },
          { label: '1.25x', value: '1.25' },
          { label: '1.5x', value: '1.5' },
          { label: '2x', value: '2' },
        ],
      },
      {
        key: 'outputFormat',
        label: 'Output format',
        type: 'select',
        defaultValue: 'mp3',
        options: [
          { label: 'MP3', value: 'mp3' },
          { label: 'WAV', value: 'wav' },
          { label: 'M4A', value: 'm4a' },
          { label: 'AAC', value: 'aac' },
        ],
      },
    ],
  },
  {
    id: 'audio-pitch-change',
    name: 'Audio Pitch Change',
    category: 'audio',
    description: 'Shift audio pitch up or down by semitone steps.',
    accept: '.mp3,.wav,.m4a,.aac,.webm,.ogg,.flac',
    tags: ['audio', 'pitch', 'tune'],
    browseGroups: ['new', 'editor-enabled'],
    previewKind: 'audio',
    options: [
      { key: 'semitones', label: 'Semitones', type: 'number', defaultValue: 2, min: -12, max: 12, step: 1 },
      {
        key: 'outputFormat',
        label: 'Output format',
        type: 'select',
        defaultValue: 'mp3',
        options: [
          { label: 'MP3', value: 'mp3' },
          { label: 'WAV', value: 'wav' },
          { label: 'M4A', value: 'm4a' },
          { label: 'AAC', value: 'aac' },
        ],
      },
    ],
  },
  {
    id: 'm4a-mp3',
    name: 'M4A to MP3',
    category: 'audio',
    description: 'Convert M4A audio files to MP3.',
    accept: '.m4a',
    tags: ['audio', 'm4a', 'mp3'],
    hiddenFromBrowse: true,
  },
  {
    id: 'm4a-wav',
    name: 'M4A to WAV',
    category: 'audio',
    description: 'Convert M4A audio files to WAV.',
    accept: '.m4a',
    tags: ['audio', 'm4a', 'wav'],
    hiddenFromBrowse: true,
  },
  {
    id: 'aac-mp3',
    name: 'AAC to MP3',
    category: 'audio',
    description: 'Convert AAC audio files to MP3.',
    accept: '.aac',
    tags: ['audio', 'aac', 'mp3'],
    hiddenFromBrowse: true,
  },
  {
    id: 'webm-mp3',
    name: 'WEBM to MP3',
    category: 'audio',
    description: 'Convert WEBM audio files to MP3.',
    accept: '.webm',
    tags: ['audio', 'webm', 'mp3'],
    hiddenFromBrowse: true,
  },
  {
    id: 'mp4-wav',
    name: 'MP4 to WAV',
    category: 'audio',
    description: 'Extract WAV audio from MP4 files.',
    accept: '.mp4',
    tags: ['audio', 'mp4', 'wav'],
    hiddenFromBrowse: true,
  },
  {
    id: 'screen-recorder',
    name: 'Screen Recorder',
    category: 'screen',
    description: 'Record an entire screen, browser tab, or app window with live preview.',
    accept: '*',
    tags: ['screen', 'record', 'capture'],
    browseGroups: ['new', 'capture', 'editor-enabled'],
    inputMode: 'capture',
    previewKind: 'video',
  },
  {
    id: 'screen-audio-recorder',
    name: 'Screen + Audio Recorder',
    category: 'screen',
    description: 'Record screen video together with system audio when the browser allows it.',
    accept: '*',
    tags: ['screen', 'record', 'audio'],
    browseGroups: ['new', 'capture', 'editor-enabled'],
    inputMode: 'capture',
    previewKind: 'video',
  },
  {
    id: 'screen-mic-recorder',
    name: 'Screen + Mic Recorder',
    category: 'screen',
    description: 'Record the screen and mix in microphone audio.',
    accept: '*',
    tags: ['screen', 'record', 'microphone'],
    browseGroups: ['new', 'capture', 'editor-enabled'],
    inputMode: 'capture',
    previewKind: 'video',
  },
  {
    id: 'screen-camera-recorder',
    name: 'Screen + Camera Recorder',
    category: 'screen',
    description: 'Record the screen with a webcam overlay composited in the browser.',
    accept: '*',
    tags: ['screen', 'camera', 'overlay'],
    browseGroups: ['new', 'capture', 'editor-enabled'],
    inputMode: 'capture',
    previewKind: 'video',
    options: [
      {
        key: 'cameraPosition',
        label: 'Camera position',
        type: 'select',
        defaultValue: 'bottom-right',
        options: [
          { label: 'Top left', value: 'top-left' },
          { label: 'Top right', value: 'top-right' },
          { label: 'Bottom left', value: 'bottom-left' },
          { label: 'Bottom right', value: 'bottom-right' },
        ],
      },
      {
        key: 'cameraScale',
        label: 'Camera size',
        type: 'range',
        defaultValue: 0.24,
        min: 0.12,
        max: 0.42,
        step: 0.02,
      },
    ],
  },
  {
    id: 'webcam-recorder',
    name: 'Webcam Recorder',
    category: 'screen',
    description: 'Record webcam video directly in the browser.',
    accept: '*',
    tags: ['camera', 'webcam', 'record'],
    browseGroups: ['new', 'capture', 'editor-enabled'],
    inputMode: 'capture',
    previewKind: 'video',
    options: [{ key: 'includeMicrophone', label: 'Include microphone', type: 'checkbox', defaultValue: true }],
  },
  {
    id: 'audio-recorder',
    name: 'Audio Recorder',
    category: 'audio',
    description: 'Record microphone audio, review the waveform, and export WAV or MP3 locally.',
    accept: '*',
    tags: ['audio', 'microphone', 'record'],
    browseGroups: ['new', 'capture', 'editor-enabled'],
    inputMode: 'capture',
    previewKind: 'audio',
    options: [
      {
        key: 'trimMode',
        label: 'Selection mode',
        type: 'select',
        defaultValue: 'keep',
        options: [
          { label: 'Keep selection', value: 'keep' },
          { label: 'Remove selection', value: 'remove' },
        ],
      },
      {
        key: 'outputFormat',
        label: 'Output format',
        type: 'select',
        defaultValue: 'wav',
        options: [
          { label: 'WAV', value: 'wav' },
          { label: 'MP3', value: 'mp3' },
        ],
      },
    ],
  },
  {
    id: 'screenshot-capture',
    name: 'Screenshot Capture',
    category: 'screen',
    description: 'Capture a still screenshot from a chosen screen or browser tab.',
    accept: '*',
    tags: ['screen', 'screenshot', 'capture'],
    browseGroups: ['new', 'capture', 'editor-enabled'],
    inputMode: 'capture',
    previewKind: 'image',
    options: [
      {
        key: 'format',
        label: 'Output format',
        type: 'select',
        defaultValue: 'image/png',
        options: [
          { label: 'PNG', value: 'image/png' },
          { label: 'JPG', value: 'image/jpeg' },
        ],
      },
    ],
  },
  {
    id: 'csv-json',
    name: 'CSV to JSON',
    category: 'file',
    description: 'Convert CSV files to JSON.',
    accept: '.csv',
    tags: ['csv', 'json'],
  },
  {
    id: 'json-csv',
    name: 'JSON to CSV',
    category: 'file',
    description: 'Convert JSON files to CSV.',
    accept: '.json',
    tags: ['json', 'csv'],
  },
  {
    id: 'excel-csv',
    name: 'Excel to CSV',
    category: 'file',
    description: 'Convert Excel spreadsheets to CSV.',
    accept: '.xls,.xlsx',
    tags: ['excel', 'csv'],
  },
  {
    id: 'csv-excel',
    name: 'CSV to Excel',
    category: 'file',
    description: 'Convert CSV files to Excel workbooks.',
    accept: '.csv',
    tags: ['csv', 'excel'],
  },
  {
    id: 'xml-json',
    name: 'XML to JSON',
    category: 'file',
    description: 'Convert XML files to JSON.',
    accept: '.xml',
    tags: ['xml', 'json'],
  },
  {
    id: 'json-xml',
    name: 'JSON to XML',
    category: 'file',
    description: 'Convert JSON files to XML.',
    accept: '.json',
    tags: ['json', 'xml'],
  },
  {
    id: 'xml-csv',
    name: 'XML to CSV',
    category: 'file',
    description: 'Convert XML data to CSV.',
    accept: '.xml',
    tags: ['xml', 'csv'],
  },
  {
    id: 'split-csv',
    name: 'Split CSV',
    category: 'file',
    description: 'Split a CSV into multiple files by row count.',
    accept: '.csv',
    tags: ['csv', 'split'],
    options: [
      { key: 'rowsPerFile', label: 'Rows per file', type: 'number', defaultValue: 1000, min: 10 },
    ],
  },
  {
    id: 'create-zip',
    name: 'Create ZIP',
    category: 'file',
    description: 'Bundle multiple files into a ZIP archive.',
    accept: '*',
    multiple: true,
    tags: ['zip', 'compress'],
    browseGroups: ['compress'],
  },
  {
    id: 'extract-zip',
    name: 'Extract ZIP',
    category: 'file',
    description: 'Extract files from a ZIP archive.',
    accept: '.zip',
    tags: ['zip', 'extract'],
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    category: 'web',
    description: 'Generate a QR code from text or a URL.',
    accept: '*',
    tags: ['qr', 'web'],
    inputMode: 'url',
    browseGroups: ['capture'],
    options: [
      { key: 'content', label: 'QR content', type: 'text', defaultValue: 'https://example.com' },
      { key: 'size', label: 'Size (px)', type: 'number', defaultValue: 320, min: 64, max: 2048 },
    ],
  },
  {
    id: 'url-image',
    name: 'URL to Image',
    category: 'web',
    description: 'Capture readable HTML from a URL into an image.',
    accept: '*',
    tags: ['url', 'screenshot', 'image'],
    inputMode: 'url',
    browseGroups: ['capture'],
    options: [
      { key: 'url', label: 'Target URL', type: 'text', defaultValue: 'https://example.com' },
      { key: 'width', label: 'Canvas width', type: 'number', defaultValue: 1200, min: 320, max: 4096 },
      { key: 'captureFullPage', label: 'Capture full page scroll', type: 'checkbox', defaultValue: true },
    ],
  },
  {
    id: 'url-pdf',
    name: 'URL to PDF',
    category: 'web',
    description: 'Capture readable HTML from a URL into a PDF.',
    accept: '*',
    tags: ['url', 'pdf', 'web'],
    inputMode: 'url',
    browseGroups: ['capture'],
    options: [
      { key: 'url', label: 'Target URL', type: 'text', defaultValue: 'https://example.com' },
      { key: 'width', label: 'Canvas width', type: 'number', defaultValue: 1200, min: 320, max: 4096 },
    ],
  },
  {
    id: 'detect-cms',
    name: 'Detect CMS',
    category: 'web',
    description: 'Inspect HTML for common CMS fingerprints.',
    accept: '*',
    tags: ['cms', 'web', 'detect'],
    inputMode: 'url',
    browseGroups: ['capture'],
    options: [
      { key: 'url', label: 'Target URL', type: 'text', defaultValue: 'https://example.com' },
    ],
  },
  {
    id: 'image-metadata',
    name: 'Image Metadata Viewer',
    category: 'web',
    description: 'Inspect metadata embedded in image files.',
    accept: 'image/*',
    tags: ['image', 'metadata'],
  },
];

export const categories: ToolCategoryDefinition[] = [
  {
    id: 'pdf',
    label: 'PDF Tools',
    description: 'Merge, split, reorder, convert, and optimize PDF files.',
    tools: [
      'pdf-merge',
      'pdf-split',
      'pdf-rearrange',
      'pdf-rotate',
      'pdf-delete-page',
      'pdf-add-page-numbers',
      'pdf-watermark',
      'pdf-redact',
      'pdf-extract-images',
      'pdf-compress',
      'pdf-to-png',
      'pdf-to-jpg',
      'pdf-to-webp',
      'image-to-pdf',
    ],
  },
  {
    id: 'image',
    label: 'Image Tools',
    description: 'Resize, convert, edit, combine, and stylize images.',
    tools: [
      'image-resize',
      'image-compress',
      'image-crop',
      'image-flip',
      'image-rotate',
      'image-pixelate',
      'image-add-text',
      'image-add-border',
      'image-split',
      'image-combine',
      'image-collage',
      'image-background-transparent',
      'image-blur-background',
      'image-upscale',
      'image-watermark',
      'image-color-palette-extract',
      'image-auto-enhance',
      'png-jpg',
      'jpg-png',
      'png-webp',
      'webp-png',
      'webp-jpg',
      'jpg-webp',
      'gif-jpg',
      'gif-png',
      'tiff-jpg',
      'tiff-png',
      'svg-png',
    ],
  },
  {
    id: 'ocr',
    label: 'OCR Tools',
    description: 'Extract visible text from images and PDFs.',
    tools: ['ocr-image-to-text', 'ocr-pdf-to-text'],
  },
  {
    id: 'video',
    label: 'Video Tools',
    description: 'Convert, compress, mute, and extract media from video files.',
    tools: [
      'video-to-gif',
      'video-to-webp',
      'mute-video',
      'extract-audio',
      'video-compress',
      'video-convert',
      'video-speed-change',
      'video-crop',
      'video-resize',
      'video-watermark',
      'video-reverse',
      'video-thumbnail-generator',
      'images-to-gif',
      'gif-to-video',
      'gif-speed-change',
      'gif-reverse',
      'gif-frame-extract',
      'mp4-webm',
      'mp4-mov',
      'mov-mp4',
      'avi-mp4',
    ],
  },
  {
    id: 'audio',
    label: 'Audio Tools',
    description: 'Convert and edit audio with a browser-first workflow.',
    tools: [
      'audio-convert',
      'audio-cut',
      'audio-merge',
      'audio-fade',
      'audio-speed-change',
      'audio-pitch-change',
      'audio-recorder',
      'm4a-mp3',
      'm4a-wav',
      'aac-mp3',
      'webm-mp3',
      'mp4-wav',
    ],
  },
  {
    id: 'screen',
    label: 'Screen Recording Tools',
    description: 'Record screens, webcams, microphones, and screenshots in the browser.',
    tools: [
      'screen-recorder',
      'screen-audio-recorder',
      'screen-mic-recorder',
      'screen-camera-recorder',
      'webcam-recorder',
      'screenshot-capture',
    ],
  },
  {
    id: 'file',
    label: 'File and Data Tools',
    description: 'Convert structured data, split CSV files, and work with ZIP archives.',
    tools: [
      'csv-json',
      'json-csv',
      'excel-csv',
      'csv-excel',
      'xml-json',
      'json-xml',
      'xml-csv',
      'split-csv',
      'create-zip',
      'extract-zip',
    ],
  },
  {
    id: 'web',
    label: 'Web Tools',
    description: 'Generate QR codes, capture URLs, detect CMS signatures, and inspect image metadata.',
    tools: ['qr-generator', 'url-image', 'url-pdf', 'detect-cms', 'image-metadata'],
  },
];

const toolById = new Map(tools.map((tool) => [tool.id, tool]));
const quickStartToolIds = ['pdf-merge', 'image-compress', 'audio-convert', 'video-to-gif', 'url-pdf'] as const;

export function getToolById(toolId: string): ToolDefinition | undefined {
  return toolById.get(toolId);
}

export function getToolsByCategory(categoryId: string, { includeHidden = true }: { includeHidden?: boolean } = {}): ToolDefinition[] {
  return tools.filter((tool) => tool.category === categoryId && (includeHidden || !tool.hiddenFromBrowse));
}

export function getBrowsableTools(): ToolDefinition[] {
  return tools.filter((tool) => !tool.hiddenFromBrowse);
}

export function getToolsByBrowseGroup(group: NonNullable<ToolDefinition['browseGroups']>[number]): ToolDefinition[] {
  return getBrowsableTools().filter((tool) => tool.browseGroups?.includes(group));
}

export function getQuickStartTools(): ToolDefinition[] {
  return quickStartToolIds.map((toolId) => getToolById(toolId)).filter((tool): tool is ToolDefinition => Boolean(tool));
}
