import {
  ArrowDownUp,
  ArrowLeftRight,
  AudioLines,
  AudioWaveform,
  BadgeCheck,
  Braces,
  Camera,
  Code,
  Columns2,
  Combine,
  Crop,
  Eraser,
  EyeOff,
  FileCode2,
  FileDown,
  FileImage,
  FilePen,
  FileSearch,
  FileSpreadsheet,
  FileText,
  FileType2,
  Film,
  FlipHorizontal2,
  Focus,
  FolderArchive,
  Frame,
  Gauge,
  GitCompare,
  Grid3x3,
  Hash,
  ImageDown,
  ImagePlus,
  Images,
  Info,
  LayoutDashboard,
  Merge,
  Mic,
  Minimize2,
  MonitorPlay,
  MonitorSpeaker,
  Music,
  PackageOpen,
  Palette,
  PanelsTopLeft,
  Presentation,
  QrCode,
  RefreshCw,
  Rewind,
  RotateCw,
  Scaling,
  ScanSearch,
  ScanText,
  Scissors,
  Signature,
  Split,
  SquareSplitHorizontal,
  Stamp,
  Table,
  TableProperties,
  Trash2,
  Type,
  VolumeX,
  WandSparkles,
  Webcam,
  Wrench,
  ZoomIn,
  type LucideIcon,
} from 'lucide-react';
import { categoryIcons } from '@/lib/tool-presentation';
import type { ToolCategory } from '@/types/tool';

/** One recognisable glyph per tool, so a category grid can be scanned at a glance. */
const toolIcons: Record<string, LucideIcon> = {
  'pdf-merge': Combine,
  'pdf-split': Scissors,
  'pdf-rearrange': ArrowDownUp,
  'pdf-rotate': RotateCw,
  'pdf-delete-page': Trash2,
  'pdf-add-page-numbers': Hash,
  'pdf-watermark': Stamp,
  'pdf-redact': EyeOff,
  'pdf-extract-images': Images,
  'pdf-compress': Minimize2,
  'pdf-reduce-size': FileDown,
  'pdf-to-png': FileImage,
  'pdf-to-jpg': FileImage,
  'pdf-to-webp': FileImage,
  'pdf-to-image': FileImage,
  'image-to-pdf': ImagePlus,
  'pdf-to-word': FileText,
  'pdf-to-excel': FileSpreadsheet,
  'word-to-pdf': FileType2,
  'powerpoint-to-pdf': Presentation,
  'excel-to-pdf': TableProperties,
  'html-to-pdf': FileCode2,
  'edit-pdf': FilePen,
  'pdf-sign': Signature,
  'pdf-repair': Wrench,
  'pdf-compare': GitCompare,
  'pdf-to-pdfa': BadgeCheck,
  'pdf-to-hwpx': ArrowLeftRight,

  'image-resize': Scaling,
  'image-compress': Minimize2,
  'image-crop': Crop,
  'image-flip': FlipHorizontal2,
  'image-rotate': RotateCw,
  'image-pixelate': Grid3x3,
  'image-add-text': Type,
  'image-add-border': Frame,
  'image-split': SquareSplitHorizontal,
  'image-combine': Columns2,
  'image-collage': LayoutDashboard,
  'image-background-transparent': Eraser,
  'image-blur-background': Focus,
  'image-upscale': ZoomIn,
  'image-watermark': Stamp,
  'image-color-palette-extract': Palette,
  'image-auto-enhance': WandSparkles,
  'image-convert': RefreshCw,
  'png-jpg': RefreshCw,
  'jpg-png': RefreshCw,
  'png-webp': RefreshCw,
  'webp-png': RefreshCw,
  'webp-jpg': RefreshCw,
  'jpg-webp': RefreshCw,
  'gif-jpg': RefreshCw,
  'gif-png': RefreshCw,
  'tiff-jpg': RefreshCw,
  'tiff-png': RefreshCw,
  'svg-png': RefreshCw,

  'ocr-image-to-text': ScanText,
  'ocr-pdf-to-text': FileSearch,

  'mute-video': VolumeX,
  'extract-audio': Music,
  'video-compress': Minimize2,
  'video-speed-change': Gauge,
  'video-trim': Scissors,
  'video-crop': Crop,
  'video-resize': Scaling,
  'video-watermark': Stamp,
  'video-reverse': Rewind,
  'video-thumbnail-generator': ImageDown,
  'video-convert': RefreshCw,
  'images-to-gif': Film,
  'gif-speed-change': Gauge,
  'gif-reverse': Rewind,
  'gif-frame-extract': Images,

  'audio-convert': RefreshCw,
  'audio-cut': Scissors,
  'audio-merge': Merge,
  'audio-fade': AudioWaveform,
  'audio-speed-change': Gauge,
  'audio-pitch-change': AudioLines,
  'audio-recorder': Mic,

  'screen-recorder': MonitorPlay,
  'screen-audio-recorder': MonitorSpeaker,
  'screen-mic-recorder': Mic,
  'screen-camera-recorder': PanelsTopLeft,
  'webcam-recorder': Webcam,
  'screenshot-capture': Camera,

  'csv-json': Braces,
  'json-csv': Table,
  'excel-csv': FileSpreadsheet,
  'csv-excel': TableProperties,
  'xml-json': Code,
  'json-xml': Code,
  'xml-csv': Table,
  'split-csv': Split,
  'create-zip': FolderArchive,
  'extract-zip': PackageOpen,

  'qr-generator': QrCode,
  'url-image': ImageDown,
  'url-pdf': FileDown,
  'detect-cms': ScanSearch,
  'image-metadata': Info,
};

export function getToolIcon(toolId: string, category: ToolCategory): LucideIcon {
  return toolIcons[toolId] ?? categoryIcons[category];
}
