'use client';

export type AudioEditorLocale = 'en' | 'ko';

const audioEditorCopy = {
  en: {
    toolbar: {
      modeLabel: 'Audio editor workspace',
      title: 'Professional audio editing, recording, and export',
      subtitle: 'Trim, preview effects, record from your microphone, and move into batch conversion when needed.',
      openFiles: 'Open audio',
      undo: 'Undo',
      redo: 'Redo',
      showEffects: 'Show effects',
      hideEffects: 'Hide effects',
      exportWav: 'Save WAV',
      exportMp3: 'Save MP3',
      reset: 'Reset',
      batch: 'File conversion',
      startRecording: 'Start recording',
      stopRecording: 'Stop recording',
    },
    fileDrop: {
      title: 'Import audio',
      description: 'Bring in an audio file for waveform editing, preview, and export.',
      helperText: 'Supported formats: MP3, WAV, M4A, AAC, OGG, FLAC, WEBM, and MP4 audio tracks.',
      dragSingle: 'Drag one audio file here',
      dragMultiple: 'Drag multiple audio files here',
      loadedFiles: 'Loaded files',
      defaultMime: 'audio',
      emptyState: 'Drop an audio file to start building the editor timeline.',
      fileTooLarge: (fileName: string) => `"${fileName}" exceeds the 500MB editor limit.`,
      largeFileWarning: 'Large audio files may take longer to decode and render in the browser.',
    },
    recording: {
      liveTitle: 'Microphone recording',
      liveDescription: 'Record directly in the browser. When you stop, the take opens in the editor automatically.',
      liveStatus: (seconds: number) => `Recording live (${seconds.toFixed(1)}s)`,
      idleStatus: 'Recorder ready',
      startError: 'Microphone recording is unavailable in this browser.',
      permissionError: 'Microphone permission is required to start recording.',
      starting: 'Preparing microphone recording...',
      finishing: 'Finalizing the recording...',
      ready: (fileName: string) => `Recording ready: ${fileName}`,
      abandoned: 'Recording was stopped.',
    },
    status: {
      loading: (fileName: string) => `Loading ${fileName}...`,
      loaded: (fileName: string, sizeLabel: string) => `Loaded ${fileName} (${sizeLabel}).`,
      decodeFailed: 'Unable to decode this audio file in the browser.',
      loadFirst: 'Load an audio file first.',
      exportPreparing: (format: 'wav' | 'mp3') => `Preparing ${format.toUpperCase()} export...`,
      exportReady: (format: 'wav' | 'mp3') => `${format.toUpperCase()} export is ready.`,
      exportFailed: 'Audio export failed.',
      playbackFailed: 'Playback failed.',
      selectedAll: 'Selected the entire waveform.',
      selectionCleared: 'Selection cleared.',
      selectionCopied: 'Selection times copied.',
      selectionReset: 'Selection reset to the full file.',
      resetDefaults: 'Editor reset to defaults.',
      undoApplied: 'Undo applied.',
      redoApplied: 'Redo applied.',
      previewFade: 'Previewing fade on the selected range.',
      previewSpeed: 'Previewing speed change on the selected range.',
      previewPitch: 'Previewing pitch shift on the selected range.',
      previewAmplify: 'Previewing amplification on the selected range.',
      previewEq: 'Previewing EQ on the selected range.',
      eqQueued: 'EQ preview is live now. Offline EQ apply is queued for the next audio-editor pass.',
      effectApplied: (label: string) => `${label} applied.`,
      decoding: 'Decoding audio buffer and preparing waveform preview...',
      waitingInput: 'Waiting for audio input.',
    },
    transport: {
      rewind: '-5s',
      play: 'Play',
      pause: 'Pause',
      stop: 'Stop',
      forward: '+5s',
      loopOn: 'Loop on',
      loopOff: 'Loop off',
      zoom: 'Zoom',
    },
    time: {
      label: 'Time',
    },
    selection: {
      kicker: 'Selection',
      title: 'Trim, keep, or remove a range',
      start: 'Start',
      end: 'End',
      length: 'Length',
      keepMode: 'Keep selection',
      removeMode: 'Remove selection',
      playSelection: 'Play selection',
      keepSelection: 'Keep selection',
      removeSelection: 'Remove selection',
      copyTimes: 'Copy times',
      clear: 'Clear',
    },
    effects: {
      kicker: 'Effects',
      title: 'Shape the audio before export',
      fade: 'Fade',
      speed: 'Speed',
      pitch: 'Pitch',
      amplify: 'Amplify',
      eq: 'EQ',
      fadeIn: 'Fade in',
      fadeOut: 'Fade out',
      playbackSpeed: 'Playback speed',
      pitchShift: 'Pitch shift',
      semitones: 'semitones',
      amplifyGain: 'Gain',
      amplifyHint: 'Boost or reduce the selected range before export. Strong boosts can clip loud material.',
      previewFade: 'Preview fade',
      applyFade: 'Apply fade',
      previewSpeed: 'Preview speed',
      applySpeed: 'Apply speed',
      previewPitch: 'Preview pitch',
      applyPitch: 'Apply pitch',
      previewAmplify: 'Preview amplify',
      applyAmplify: 'Apply amplify',
      pitchHint: 'Pitch preview is staged first. Precise time-stretch correction can be added in a later iteration.',
      low: 'Low',
      mid: 'Mid',
      high: 'High',
      eqHint: 'EQ is staged as UI in this first step. The panel is ready for a later Web Audio filter chain.',
      previewEq: 'Preview EQ',
      applyEq: 'Apply EQ',
    },
    waveform: {
      timeline: 'Timeline',
      silentNotice: 'Silent or very quiet audio detected. You can still trim and export this file.',
    },
    session: {
      kicker: 'Session',
      activeFile: (fileName: string) => `Active file: ${fileName}`,
      noFile: 'No file loaded yet.',
      duration: (durationLabel: string, sampleRate: number) =>
        `Duration: ${durationLabel} | Sample rate: ${sampleRate.toLocaleString()} Hz`,
      undoDepth: (depth: number, zoom: number) => `Undo depth: ${depth} | Zoom: x${zoom.toFixed(1)}`,
      shortcutsTitle: 'Quick actions',
      shortcutsDescription: 'Save the current edit or move into the dedicated batch conversion workspace.',
      batchLink: 'Open file conversion',
      saveHint: 'Save buttons stay visible in the top toolbar for quick export.',
    },
    commands: {
      keepSelection: 'Keep selection',
      removeSelection: 'Remove selection',
      fadeEnvelope: 'Fade envelope',
      speedChange: 'Speed change',
      pitchShift: 'Pitch shift',
      amplify: 'Amplify',
    },
  },
  ko: {
    toolbar: {
      modeLabel: '오디오 편집 작업공간',
      title: '전문형 오디오 편집, 녹음, 저장',
      subtitle: '자르기, 효과 미리듣기, 마이크 녹음, 파일 변환 이동까지 한 화면에서 처리합니다.',
      openFiles: '오디오 열기',
      undo: '실행 취소',
      redo: '다시 실행',
      showEffects: '효과 열기',
      hideEffects: '효과 숨기기',
      exportWav: 'WAV 저장',
      exportMp3: 'MP3 저장',
      reset: '초기화',
      batch: '파일 변환',
      startRecording: '녹음 시작',
      stopRecording: '녹음 중지',
    },
    fileDrop: {
      title: '오디오 불러오기',
      description: '오디오 파일을 가져와 파형 편집, 미리듣기, 저장까지 진행하세요.',
      helperText: '지원 형식: MP3, WAV, M4A, AAC, OGG, FLAC, WEBM, MP4 오디오 트랙',
      dragSingle: '오디오 파일 1개를 여기에 드래그하세요',
      dragMultiple: '오디오 파일 여러 개를 여기에 드래그하세요',
      loadedFiles: '불러온 파일',
      defaultMime: '오디오',
      emptyState: '오디오 파일을 넣으면 타임라인 편집이 시작됩니다.',
      fileTooLarge: (fileName: string) => `"${fileName}" 파일은 500MB 편집 한도를 초과했습니다.`,
      largeFileWarning: '용량이 큰 오디오 파일은 브라우저에서 디코딩과 파형 렌더링에 시간이 더 걸릴 수 있습니다.',
    },
    recording: {
      liveTitle: '마이크 녹음',
      liveDescription: '브라우저에서 바로 녹음하고, 중지하면 결과가 자동으로 편집기에 열립니다.',
      liveStatus: (seconds: number) => `녹음 중 (${seconds.toFixed(1)}초)`,
      idleStatus: '녹음 대기 중',
      startError: '이 브라우저에서는 마이크 녹음을 사용할 수 없습니다.',
      permissionError: '녹음을 시작하려면 마이크 권한이 필요합니다.',
      starting: '마이크 녹음을 준비하는 중...',
      finishing: '녹음을 마무리하는 중...',
      ready: (fileName: string) => `녹음 파일 준비 완료: ${fileName}`,
      abandoned: '녹음을 중지했습니다.',
    },
    status: {
      loading: (fileName: string) => `${fileName} 파일을 불러오는 중...`,
      loaded: (fileName: string, sizeLabel: string) => `${fileName} 불러오기 완료 (${sizeLabel})`,
      decodeFailed: '브라우저에서 이 오디오 파일을 디코딩할 수 없습니다.',
      loadFirst: '먼저 오디오 파일을 불러오세요.',
      exportPreparing: (format: 'wav' | 'mp3') => `${format.toUpperCase()} 저장을 준비하는 중...`,
      exportReady: (format: 'wav' | 'mp3') => `${format.toUpperCase()} 파일이 저장 준비되었습니다.`,
      exportFailed: '오디오 저장에 실패했습니다.',
      playbackFailed: '재생에 실패했습니다.',
      selectedAll: '전체 파형을 선택했습니다.',
      selectionCleared: '선택 영역을 해제했습니다.',
      selectionCopied: '선택 구간 시간을 복사했습니다.',
      selectionReset: '선택 영역을 전체 파일 기준으로 되돌렸습니다.',
      resetDefaults: '편집기 설정을 기본값으로 되돌렸습니다.',
      undoApplied: '실행 취소를 적용했습니다.',
      redoApplied: '다시 실행을 적용했습니다.',
      previewFade: '선택 구간에 페이드를 미리듣는 중입니다.',
      previewSpeed: '선택 구간의 속도 변화를 미리듣는 중입니다.',
      previewPitch: '선택 구간의 피치 변화를 미리듣는 중입니다.',
      previewAmplify: '선택 구간의 볼륨 증폭을 미리듣는 중입니다.',
      previewEq: '선택 구간의 EQ를 미리듣는 중입니다.',
      eqQueued: 'EQ는 지금 미리듣기만 지원하며, 오프라인 적용은 다음 오디오 편집 단계에서 추가됩니다.',
      effectApplied: (label: string) => `${label} 적용 완료`,
      decoding: '오디오 버퍼를 디코딩하고 파형을 준비하는 중...',
      waitingInput: '오디오 입력을 기다리는 중입니다.',
    },
    transport: {
      rewind: '-5초',
      play: '재생',
      pause: '일시정지',
      stop: '정지',
      forward: '+5초',
      loopOn: '루프 켜짐',
      loopOff: '루프 꺼짐',
      zoom: '확대',
    },
    time: {
      label: '시간',
    },
    selection: {
      kicker: '선택',
      title: '구간을 잘라내거나 남길 수 있습니다',
      start: '시작',
      end: '끝',
      length: '길이',
      keepMode: '선택 구간만 남기기',
      removeMode: '선택 구간 제거',
      playSelection: '선택 구간 재생',
      keepSelection: '선택 구간만 남기기',
      removeSelection: '선택 구간 제거',
      copyTimes: '시간 복사',
      clear: '해제',
    },
    effects: {
      kicker: '효과',
      title: '저장 전에 오디오를 다듬기',
      fade: '페이드',
      speed: '속도',
      pitch: '피치',
      amplify: '앰플리파이',
      eq: 'EQ',
      fadeIn: '페이드 인',
      fadeOut: '페이드 아웃',
      playbackSpeed: '재생 속도',
      pitchShift: '피치 이동',
      semitones: '반음',
      amplifyGain: '증폭 배율',
      amplifyHint: '선택 구간의 볼륨을 키우거나 줄일 수 있습니다. 너무 크게 올리면 클리핑이 생길 수 있습니다.',
      previewFade: '페이드 미리듣기',
      applyFade: '페이드 적용',
      previewSpeed: '속도 미리듣기',
      applySpeed: '속도 적용',
      previewPitch: '피치 미리듣기',
      applyPitch: '피치 적용',
      previewAmplify: '앰플리파이 미리듣기',
      applyAmplify: '앰플리파이 적용',
      pitchHint: '피치 미리듣기를 먼저 제공하며, 정밀한 시간 보정은 다음 단계에서 확장할 수 있습니다.',
      low: '저역',
      mid: '중역',
      high: '고역',
      eqHint: '이번 단계에서는 EQ UI와 미리듣기 중심으로 제공됩니다. 오프라인 적용 체인은 다음 단계에서 확장할 예정입니다.',
      previewEq: 'EQ 미리듣기',
      applyEq: 'EQ 적용',
    },
    waveform: {
      timeline: '타임라인',
      silentNotice: '무음이거나 매우 작은 오디오입니다. 그래도 자르기와 저장은 정상적으로 할 수 있습니다.',
    },
    session: {
      kicker: '세션',
      activeFile: (fileName: string) => `현재 파일: ${fileName}`,
      noFile: '아직 불러온 파일이 없습니다.',
      duration: (durationLabel: string, sampleRate: number) =>
        `길이: ${durationLabel} | 샘플레이트: ${sampleRate.toLocaleString()} Hz`,
      undoDepth: (depth: number, zoom: number) => `실행 취소 단계: ${depth} | 확대: x${zoom.toFixed(1)}`,
      shortcutsTitle: '빠른 작업',
      shortcutsDescription: '현재 편집본을 저장하거나, 전용 파일 변환 화면으로 이동할 수 있습니다.',
      batchLink: '파일 변환 열기',
      saveHint: '빠른 저장 버튼은 상단 툴바에 항상 표시됩니다.',
    },
    commands: {
      keepSelection: '선택 구간만 남기기',
      removeSelection: '선택 구간 제거',
      fadeEnvelope: '페이드',
      speedChange: '속도 변경',
      pitchShift: '피치 변경',
      amplify: '앰플리파이',
    },
  },
} as const;

export type AudioEditorCopy = (typeof audioEditorCopy)[AudioEditorLocale];

export function getAudioEditorCopy(locale: AudioEditorLocale): AudioEditorCopy {
  return audioEditorCopy[locale] ?? audioEditorCopy.en;
}
