'use client';

export type AudioEditorLocale = 'en' | 'ko';

const audioEditorCopy = {
  en: {
    toolbar: {
      openFiles: 'Open audio',
      exportWav: 'Save WAV',
      exportMp3: 'Save MP3',
      reset: 'Reset editor',
      batch: 'Open file conversion',
      startRecording: 'Start recording',
      stopRecording: 'Stop recording',
      pauseRecording: 'Pause recording',
      resumeRecording: 'Resume recording',
      showEffects: 'Show effects',
      hideEffects: 'Hide effects',
      more: 'More actions',
      shortcuts: 'Shortcuts',
      shortcutHint: 'Space play/pause, arrows nudge the playhead, Ctrl/Cmd+Z undo, Ctrl/Cmd+Y redo.',
      loopOn: 'Loop enabled',
      loopOff: 'Loop disabled',
    },
    fileDrop: {
      title: 'Import audio',
      description: 'Drop a file here to open the waveform workspace.',
      helperText: 'Supported formats: MP3, WAV, M4A, AAC, OGG, FLAC, WEBM, and MP4 audio tracks.',
      dragSingle: 'Drag one audio file here',
      dragMultiple: 'Drag multiple audio files here',
      loadedFiles: 'Loaded files',
      defaultMime: 'audio',
      emptyState: 'Open an audio file or start a microphone recording to enter the editor.',
      fileTooLarge: (fileName: string) => `"${fileName}" exceeds the 500MB editor limit.`,
      largeFileWarning: 'Large audio files may take longer to decode and render in the browser.',
    },
    recording: {
      liveTitle: 'Microphone recording',
      liveDescription: 'Record directly in the browser. The take opens in the editor as soon as you stop.',
      liveStatus: (seconds: number) => `Recording live (${seconds.toFixed(1)}s)`,
      pausedStatus: (seconds: number) => `Recording paused (${seconds.toFixed(1)}s)`,
      idleStatus: 'Recorder ready',
      startError: 'Microphone recording is unavailable in this browser.',
      permissionError: 'Microphone permission is required to start recording.',
      starting: 'Preparing microphone recording...',
      finishing: 'Finalizing the recording...',
      ready: (fileName: string) => `Recording ready: ${fileName}`,
      abandoned: 'Recording was stopped.',
    },
    status: {
      loading: (fileName: string) => `Loading ${fileName}...`,
      loaded: (fileName: string, sizeLabel: string) => `Loaded ${fileName} (${sizeLabel}).`,
      decodeFailed: 'Unable to decode this audio file in the browser.',
      loadFirst: 'Load an audio file first.',
      exportPreparing: (format: 'wav' | 'mp3') => `Preparing ${format.toUpperCase()} export...`,
      exportReady: (format: 'wav' | 'mp3') => `${format.toUpperCase()} export is ready.`,
      exportFailed: 'Audio export failed.',
      playbackFailed: 'Playback failed.',
      selectedAll: 'Selected the entire waveform.',
      selectionCleared: 'Selection cleared.',
      selectionCopied: 'Selection times copied.',
      selectionReset: 'Selection reset to the full file.',
      resetDefaults: 'Editor reset to defaults.',
      undoApplied: 'Undo applied.',
      redoApplied: 'Redo applied.',
      previewFade: 'Previewing fade on the selected range.',
      previewSpeed: 'Previewing speed change on the selected range.',
      previewPitch: 'Previewing pitch shift on the selected range.',
      previewAmplify: 'Previewing amplification on the selected range.',
      previewReverb: 'Previewing reverb on the selected range.',
      previewEq: 'Previewing EQ on the selected range.',
      eqQueued: 'EQ preview is available now. Offline EQ apply is queued for the next audio-editor pass.',
      effectApplied: (label: string) => `${label} applied.`,
      decoding: 'Decoding audio buffer and preparing waveform preview...',
      waitingInput: 'Waiting for audio input.',
    },
    transport: {
      undo: 'Undo',
      redo: 'Redo',
      jumpStart: 'Jump to start',
      jumpEnd: 'Jump to end',
      rewind: 'Back 5 seconds',
      forward: 'Forward 5 seconds',
      play: 'Play',
      pause: 'Pause',
      zoom: 'Zoom',
    },
    time: {
      label: 'Time',
    },
    selection: {
      kicker: 'Selected range',
      activeDescription: 'Review the selected region and choose what to keep or remove.',
      inactiveDescription: 'Drag across the waveform to create a focused edit range.',
      start: 'Start',
      end: 'End',
      length: 'Length',
      playSelection: 'Play selection',
      keepSelection: 'Keep',
      removeSelection: 'Remove',
      copyTimes: 'Copy times',
      clear: 'Clear',
    },
    effects: {
      kicker: 'Effects',
      title: 'Preview and apply focused processing',
      close: 'Close effects',
      fade: 'Fade',
      speed: 'Speed',
      pitch: 'Pitch',
      amplify: 'Amplify',
      reverb: 'Reverb',
      eq: 'EQ',
      fadeIn: 'Fade in',
      fadeOut: 'Fade out',
      playbackSpeed: 'Playback speed',
      pitchShift: 'Pitch shift',
      semitones: 'semitones',
      amplifyGain: 'Gain',
      reverbDecay: 'Decay',
      reverbMix: 'Mix',
      amplifyHint: 'Boost or reduce the selected range before export. Strong boosts can clip loud material.',
      previewFade: 'Preview fade',
      applyFade: 'Apply fade',
      previewSpeed: 'Preview speed',
      applySpeed: 'Apply speed',
      previewPitch: 'Preview pitch',
      applyPitch: 'Apply pitch',
      previewAmplify: 'Preview amplify',
      applyAmplify: 'Apply amplify',
      previewReverb: 'Preview reverb',
      applyReverb: 'Apply reverb',
      reverbHint: 'Add a short room tail to place the selected audio in a wider space.',
      pitchHint: 'Pitch preview is staged first. Precise time-stretch correction can be added in a later iteration.',
      low: 'Low',
      mid: 'Mid',
      high: 'High',
      eqHint: 'EQ is preview-first in this pass. A more advanced offline apply chain can be added in the next iteration.',
      previewEq: 'Preview EQ',
      applyEq: 'Apply EQ',
      applied: 'Applied',
    },
    waveform: {
      timeline: 'Timeline',
      silentNotice: 'Silent or very quiet audio',
      loading: 'Rendering waveform...',
      dragHint: 'Drag on the waveform to create a range. Drag the handles to refine it.',
    },
    session: {
      kicker: 'Session',
      activeFile: (fileName: string) => `Active file: ${fileName}`,
      activeTrack: (trackName: string) => `Active track: ${trackName}`,
      noFile: 'No file loaded yet.',
      duration: (durationLabel: string, sampleRate: number) =>
        `Duration ${durationLabel} · ${sampleRate.toLocaleString()} Hz`,
      history: (depth: number) => `Undo steps ${depth}`,
      trackCount: (count: number) => `${count} track${count === 1 ? '' : 's'}`,
    },
    multitrack: {
      title: 'Tracks',
      addTrack: 'Add track',
      recordNewTrack: 'Record new track',
      mergeAndSave: 'Merge and save',
      track: 'Track',
      mute: 'Mute',
      solo: 'Solo',
    },
    commands: {
      keepSelection: 'Keep selection',
      removeSelection: 'Remove selection',
      fadeEnvelope: 'Fade envelope',
      speedChange: 'Speed change',
      pitchShift: 'Pitch shift',
      amplify: 'Amplify',
      reverb: 'Reverb',
    },
  },
  ko: {
    toolbar: {
      openFiles: '오디오 열기',
      exportWav: 'WAV 저장',
      exportMp3: 'MP3 저장',
      reset: '편집기 초기화',
      batch: '파일 변환 열기',
      startRecording: '녹음 시작',
      stopRecording: '녹음 중지',
      pauseRecording: '녹음 일시정지',
      resumeRecording: '녹음 이어서',
      showEffects: '효과 열기',
      hideEffects: '효과 숨기기',
      more: '더보기',
      shortcuts: '단축키',
      shortcutHint: 'Space 재생/일시정지, 방향키 플레이헤드 이동, Ctrl/Cmd+Z 실행 취소, Ctrl/Cmd+Y 다시 실행',
      loopOn: '루프 켜짐',
      loopOff: '루프 꺼짐',
    },
    fileDrop: {
      title: '오디오 불러오기',
      description: '파일을 넣으면 파형 편집 작업공간이 열립니다.',
      helperText: '지원 형식: MP3, WAV, M4A, AAC, OGG, FLAC, WEBM, MP4 오디오 트랙',
      dragSingle: '오디오 파일 1개를 여기에 드래그하세요',
      dragMultiple: '오디오 파일 여러 개를 여기에 드래그하세요',
      loadedFiles: '불러온 파일',
      defaultMime: '오디오',
      emptyState: '오디오 파일을 열거나 마이크 녹음을 시작하면 편집기가 열립니다.',
      fileTooLarge: (fileName: string) => `"${fileName}" 파일은 500MB 편집 한도를 초과했습니다.`,
      largeFileWarning: '용량이 큰 오디오 파일은 브라우저에서 디코딩과 파형 렌더링에 시간이 더 걸릴 수 있습니다.',
    },
    recording: {
      liveTitle: '마이크 녹음',
      liveDescription: '브라우저에서 바로 녹음하고, 멈추면 결과가 즉시 편집기에 열립니다.',
      liveStatus: (seconds: number) => `녹음 중 (${seconds.toFixed(1)}초)`,
      pausedStatus: (seconds: number) => `녹음 일시정지 (${seconds.toFixed(1)}초)`,
      idleStatus: '녹음 대기 중',
      startError: '이 브라우저에서는 마이크 녹음을 사용할 수 없습니다.',
      permissionError: '녹음을 시작하려면 마이크 권한이 필요합니다.',
      starting: '마이크 녹음을 준비하는 중...',
      finishing: '녹음을 마무리하는 중...',
      ready: (fileName: string) => `녹음 파일 준비 완료: ${fileName}`,
      abandoned: '녹음을 중지했습니다.',
    },
    status: {
      loading: (fileName: string) => `${fileName} 파일을 불러오는 중...`,
      loaded: (fileName: string, sizeLabel: string) => `${fileName} 불러오기 완료 (${sizeLabel})`,
      decodeFailed: '브라우저에서 이 오디오 파일을 디코딩할 수 없습니다.',
      loadFirst: '먼저 오디오 파일을 불러오세요.',
      exportPreparing: (format: 'wav' | 'mp3') => `${format.toUpperCase()} 저장을 준비하는 중...`,
      exportReady: (format: 'wav' | 'mp3') => `${format.toUpperCase()} 파일이 저장 준비되었습니다.`,
      exportFailed: '오디오 저장에 실패했습니다.',
      playbackFailed: '재생에 실패했습니다.',
      selectedAll: '전체 파형을 선택했습니다.',
      selectionCleared: '선택 구간을 해제했습니다.',
      selectionCopied: '선택 구간 시간을 복사했습니다.',
      selectionReset: '선택 구간을 전체 파일 기준으로 되돌렸습니다.',
      resetDefaults: '편집기를 기본 상태로 되돌렸습니다.',
      undoApplied: '실행 취소를 적용했습니다.',
      redoApplied: '다시 실행을 적용했습니다.',
      previewFade: '선택 구간에 페이드를 미리듣는 중입니다.',
      previewSpeed: '선택 구간의 속도 변화를 미리듣는 중입니다.',
      previewPitch: '선택 구간의 피치 변화를 미리듣는 중입니다.',
      previewAmplify: '선택 구간의 증폭을 미리듣는 중입니다.',
      previewReverb: '선택 구간의 리버브를 미리듣는 중입니다.',
      previewEq: '선택 구간의 EQ를 미리듣는 중입니다.',
      eqQueued: 'EQ는 지금 미리듣기 중심으로 제공되며, 오프라인 적용은 다음 편집 단계에서 확장됩니다.',
      effectApplied: (label: string) => `${label} 적용 완료`,
      decoding: '오디오 버퍼를 디코딩하고 파형을 준비하는 중...',
      waitingInput: '오디오 입력을 기다리는 중입니다.',
    },
    transport: {
      undo: '실행 취소',
      redo: '다시 실행',
      jumpStart: '처음으로 이동',
      jumpEnd: '끝으로 이동',
      rewind: '5초 뒤로',
      forward: '5초 앞으로',
      play: '재생',
      pause: '일시정지',
      zoom: '확대',
    },
    time: {
      label: '시간',
    },
    selection: {
      kicker: '선택 구간',
      activeDescription: '선택한 구간을 기준으로 남기기, 제거, 재생을 진행할 수 있습니다.',
      inactiveDescription: '파형 위를 드래그해서 편집할 구간을 먼저 지정하세요.',
      start: '시작',
      end: '끝',
      length: '길이',
      playSelection: '선택 재생',
      keepSelection: '남기기',
      removeSelection: '제거',
      copyTimes: '시간 복사',
      clear: '해제',
    },
    effects: {
      kicker: '효과',
      title: '효과를 미리듣고 선택 구간에 적용하기',
      close: '효과 패널 닫기',
      fade: '페이드',
      speed: '속도',
      pitch: '피치',
      amplify: '앰플리파이',
      reverb: '리버브',
      eq: 'EQ',
      fadeIn: '페이드 인',
      fadeOut: '페이드 아웃',
      playbackSpeed: '재생 속도',
      pitchShift: '피치 이동',
      semitones: '반음',
      amplifyGain: '증폭 배율',
      reverbDecay: '잔향 길이',
      reverbMix: '믹스',
      amplifyHint: '선택 구간의 볼륨을 키우거나 줄일 수 있습니다. 너무 크게 올리면 클리핑이 생길 수 있습니다.',
      previewFade: '페이드 미리듣기',
      applyFade: '페이드 적용',
      previewSpeed: '속도 미리듣기',
      applySpeed: '속도 적용',
      previewPitch: '피치 미리듣기',
      applyPitch: '피치 적용',
      previewAmplify: '앰플리파이 미리듣기',
      applyAmplify: '앰플리파이 적용',
      previewReverb: '리버브 미리듣기',
      applyReverb: '리버브 적용',
      reverbHint: '선택 구간에 짧은 잔향을 더해 공간감을 만듭니다.',
      pitchHint: '피치 미리듣기를 먼저 제공하며, 정밀한 시간 보정은 다음 단계에서 확장할 수 있습니다.',
      low: '저역',
      mid: '중역',
      high: '고역',
      eqHint: '이번 단계에서는 EQ 미리듣기 경험을 먼저 제공합니다. 더 정교한 오프라인 적용은 다음 단계에서 확장할 예정입니다.',
      previewEq: 'EQ 미리듣기',
      applyEq: 'EQ 적용',
      applied: '적용됨',
    },
    waveform: {
      timeline: '타임라인',
      silentNotice: '무음 또는 매우 조용한 오디오',
      loading: '파형을 렌더링하는 중...',
      dragHint: '파형을 드래그해 구간을 만들고, 양쪽 핸들로 더 정밀하게 조정하세요.',
    },
    session: {
      kicker: '세션',
      activeFile: (fileName: string) => `현재 파일: ${fileName}`,
      activeTrack: (trackName: string) => `현재 트랙: ${trackName}`,
      noFile: '아직 불러온 파일이 없습니다.',
      duration: (durationLabel: string, sampleRate: number) =>
        `길이 ${durationLabel} · ${sampleRate.toLocaleString()} Hz`,
      history: (depth: number) => `실행 취소 단계 ${depth}`,
      trackCount: (count: number) => `트랙 ${count}개`,
    },
    multitrack: {
      title: '트랙',
      addTrack: '트랙 추가',
      recordNewTrack: '새 트랙으로 녹음',
      mergeAndSave: '트랙 합치기 및 저장',
      track: '트랙',
      mute: '음소거',
      solo: '솔로',
    },
    commands: {
      keepSelection: '선택 구간 남기기',
      removeSelection: '선택 구간 제거',
      fadeEnvelope: '페이드',
      speedChange: '속도 변경',
      pitchShift: '피치 변경',
      amplify: '앰플리파이',
      reverb: '리버브',
    },
  },
} as const;

export type AudioEditorCopy = (typeof audioEditorCopy)[AudioEditorLocale];

export function getAudioEditorCopy(locale: AudioEditorLocale): AudioEditorCopy {
  return audioEditorCopy[locale] ?? audioEditorCopy.en;
}
